import { Ionicons } from '@expo/vector-icons';
import { useEffect, useMemo, useState } from 'react';
import { ScrollView, StyleSheet, TextInput, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { api,hasApi } from '../src/api';
import { defaultPrefs, paletteFor, type LocalPrefs } from '../src/prefs';
import { getPrefs } from '../src/session';
import { NText } from '../src/ui';

export default function Assistant(){const[q,setQ]=useState('');const[result,setResult]=useState('');const[loading,setLoading]=useState(false);const[prefs,setPrefs]=useState<LocalPrefs>(defaultPrefs);useEffect(()=>{getPrefs().then(p=>p&&setPrefs(p))},[]);const t=paletteFor(prefs.audience,prefs.appearance);const s=useMemo(()=>styles(t),[prefs.audience,prefs.appearance]);const chips=prefs.audience==='MALE'?['فردا عصر برای اصلاح ریش وقت می‌خوام','برای پوست حساس چه خدمتی مناسبه؟','برای دامادی چه پکیجی پیشنهاد می‌دی؟']:prefs.audience==='FEMALE'?['فردا عصر وقت ناخن می‌خوام','پوستم حساسه؛ چه خدمتی بهتره؟','برای مراسم یک پکیج پیشنهاد بده']:['فردا عصر وقت خالی می‌خوام','برای پوست حساس چه خدمتی مناسبه؟','یک گزینه نزدیک و خوش‌امتیاز پیشنهاد بده'];
async function send(v=q){if(!v.trim())return;setQ(v);setLoading(true);try{if(hasApi){const r=await api('/v1/ai/smart-search',{method:'POST',body:JSON.stringify({query:v})});setResult(r?.answer||'چند گزینه مرتبط پیدا شد؛ برای انتخاب دقیق‌تر محدوده و زمان را مشخص کن.')}else setResult('برای پیشنهاد دقیق‌تر، زمان، محدوده و بودجه را مشخص کن.')}catch{setResult('ارتباط با دستیار برقرار نشد. جستجوی عادی همچنان در دسترس است.')}finally{setLoading(false)}}
return <SafeAreaView edges={['bottom']} style={s.root}><ScrollView contentContainerStyle={s.wrap} keyboardShouldPersistTaps="handled"><View style={s.hero}><View style={s.icon}><Ionicons name="sparkles" size={23} color={t.accent}/></View><NText weight="bold" style={s.h}>دستیار نوبین</NText><NText style={s.heroP}>نیازت را طبیعی بنویس. پیشنهاد می‌دهم؛ رزرو یا پرداخت بدون تأیید تو انجام نمی‌شود.</NText></View><View style={s.chips}>{chips.map(x=><TouchableOpacity activeOpacity={.72} key={x} style={s.chip} onPress={()=>send(x)}><Ionicons name="arrow-back" size={16} color={t.muted}/><NText weight="medium" style={s.chipT}>{x}</NText></TouchableOpacity>)}</View><TextInput multiline style={s.input} placeholder="چه کمکی از نوبین می‌خواهی؟" placeholderTextColor={t.muted} value={q} onChangeText={setQ} textAlign="right"/><TouchableOpacity disabled={loading} activeOpacity={.75} style={[s.btn,loading&&{opacity:.55}]} onPress={()=>send()}><NText weight="bold" style={s.bt}>{loading?'در حال بررسی…':'پیشنهاد بده'}</NText></TouchableOpacity>{!!result&&<View style={s.card}><NText weight="semi" style={s.aiTitle}>پاسخ نوبین</NText><NText style={s.p}>{result}</NText><NText style={s.note}>پیشنهادهای هوشمند جایگزین نظر پزشک یا متخصص درمانی نیستند.</NText></View>}</ScrollView></SafeAreaView>}
const styles=(t:any)=>StyleSheet.create({root:{flex:1,backgroundColor:t.bg},wrap:{padding:16,paddingBottom:32,gap:11},hero:{backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:19,padding:15,gap:7},icon:{width:42,height:42,borderRadius:13,backgroundColor:t.accentSoft,alignItems:'center',justifyContent:'center'},h:{fontSize:19,color:t.text,textAlign:'right'},heroP:{fontSize:12.5,lineHeight:21,color:t.muted,textAlign:'right'},chips:{gap:7},chip:{minHeight:45,backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:14,paddingHorizontal:12,flexDirection:'row',alignItems:'center',gap:8},chipT:{flex:1,textAlign:'right',fontSize:12,color:t.text},input:{minHeight:108,backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:17,padding:13,fontFamily:'Vazirmatn_400Regular',fontSize:13.5,lineHeight:23,color:t.text,textAlignVertical:'top'},btn:{backgroundColor:t.accent,padding:13,borderRadius:14,alignItems:'center'},bt:{color:'#fff',fontSize:13},card:{backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:17,padding:14,gap:6},aiTitle:{fontSize:14,color:t.accent,textAlign:'right'},p:{fontSize:12.5,lineHeight:22,color:t.muted,textAlign:'right'},note:{fontSize:10.5,lineHeight:18,color:t.muted,textAlign:'right'}})
