import { Ionicons } from '@expo/vector-icons';
import { useEffect, useMemo, useState } from 'react';
import { Image, ScrollView, StyleSheet, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { api } from '../src/api';
import { jalaliDateTime } from '../src/dateFa';
import { effectiveAudience, paletteFor } from '../src/prefs';
import { getPrefs, getToken } from '../src/session';
import { BottomNav, NText, PageTitle } from '../src/ui';
import { defaultPrefs, type LocalPrefs } from '../src/prefs';

type FeedItem={id:string|number;title?:string;body?:string;image_url?:string;published_at?:string;business_id?:number;business_name?:string;scope?:string;author_type?:string};
export default function Blog(){const[prefs,setPrefs]=useState<LocalPrefs>(defaultPrefs);const[items,setItems]=useState<FeedItem[]>([]);const[loading,setLoading]=useState(true);const[logged,setLogged]=useState(false);const a=effectiveAudience(prefs);const t=paletteFor(a,prefs.appearance);const s=useMemo(()=>styles(t),[a,prefs.appearance]);
 const load=async()=>{const p=await getPrefs();if(p)setPrefs(p);const tok=await getToken();setLogged(Boolean(tok));try{const qs=new URLSearchParams();if(p?.preferredProvince)qs.set('province',p.preferredProvince);if(p?.preferredCity)qs.set('city',p.preferredCity);const j=await api(`/v1/feed${qs.toString()?`?${qs}`:''}`);setItems(Array.isArray(j?.items)?j.items:[])}catch{setItems([])}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 return <SafeAreaView edges={['top']} style={s.root}><ScrollView contentContainerStyle={s.wrap} showsVerticalScrollIndicator={false}><PageTitle title="بلاگ" sub="اطلاعیه‌های نوبین و مجموعه‌هایی که دنبال می‌کنی"/><View style={s.scope}><Ionicons name="location-outline" size={16} color={t.accent}/><NText style={s.scopeT}>{prefs.preferredCity?`${prefs.preferredProvince}، ${prefs.preferredCity}`:'سراسر ایران'}</NText></View>{loading?<NText style={s.muted}>در حال دریافت...</NText>:!logged?<View style={s.empty}><Ionicons name="newspaper-outline" size={34} color={t.muted}/><NText weight="semi" style={s.emptyTitle}>برای دیدن پست دنبال‌شده‌ها وارد شوید</NText><NText style={s.muted}>پیام‌های عمومی مدیر همچنان پس از اتصال سرویس نمایش داده می‌شوند.</NText><TouchableOpacity style={s.btn} onPress={()=>router.push('/login')}><NText weight="bold" style={s.btnT}>ورود با بله</NText></TouchableOpacity></View>:items.length?items.map(x=><TouchableOpacity disabled={!x.business_id} activeOpacity={.76} key={String(x.id)} style={s.card} onPress={()=>x.business_id&&router.push(`/business/${x.business_id}`)}>{x.image_url?<Image source={{uri:x.image_url}} style={s.image}/>:null}<View style={s.cardBody}><View style={s.topRow}><NText style={s.date}>{x.published_at?jalaliDateTime(x.published_at):''}</NText><NText weight="semi" style={s.author}>{x.business_name||'نوبین'}</NText></View>{x.title?<NText weight="bold" style={s.title}>{x.title}</NText>:null}<NText style={s.body}>{x.body||''}</NText>{x.author_type==='ADMIN'||x.scope?<View style={s.badge}><Ionicons name="megaphone-outline" size={13} color={t.accent}/><NText weight="medium" style={s.badgeT}>{x.scope==='GLOBAL'?'اطلاعیه سراسری':x.scope==='CITY'?'اطلاعیه شهری':x.scope==='PROVINCE'?'اطلاعیه استانی':'اطلاعیه نوبین'}</NText></View>:null}</View></TouchableOpacity>):<View style={s.empty}><Ionicons name="leaf-outline" size={34} color={t.muted}/><NText weight="semi" style={s.emptyTitle}>فعلاً مطلب تازه‌ای نیست</NText><NText style={s.muted}>وقتی مجموعه‌ای را دنبال کنی، پست‌ها و اطلاعیه‌های آن فقط در بلاگ خودت نمایش داده می‌شود. اطلاعیه‌های هدفمند مدیر نیز بر اساس محدوده انتخابی نمایش داده خواهند شد.</NText></View>}</ScrollView><BottomNav active="blog" t={t}/></SafeAreaView>}
const styles=(t:any)=>StyleSheet.create({root:{flex:1,backgroundColor:t.bg},wrap:{paddingHorizontal:18,paddingTop:10,paddingBottom:24,gap:12},scope:{alignSelf:'flex-end',height:34,borderRadius:13,backgroundColor:t.accentSoft,flexDirection:'row-reverse',alignItems:'center',gap:5,paddingHorizontal:10},scopeT:{fontSize:10.5,color:t.accent},muted:{fontSize:11.5,lineHeight:20,color:t.muted,textAlign:'right'},card:{backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:18,overflow:'hidden'},image:{width:'100%',height:160},cardBody:{padding:13,gap:7},topRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:8},author:{fontSize:12.5,color:t.text,textAlign:'right'},date:{fontSize:9.5,color:t.muted},title:{fontSize:15.5,lineHeight:25,color:t.text,textAlign:'right'},body:{fontSize:12,lineHeight:21,color:t.muted,textAlign:'right'},badge:{alignSelf:'flex-end',flexDirection:'row-reverse',alignItems:'center',gap:4,backgroundColor:t.accentSoft,borderRadius:10,paddingHorizontal:8,paddingVertical:5},badgeT:{fontSize:9.5,color:t.accent},empty:{backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:18,padding:24,alignItems:'center',gap:8},emptyTitle:{fontSize:15,color:t.text,textAlign:'center'},btn:{marginTop:4,backgroundColor:t.accent,borderRadius:14,paddingHorizontal:18,paddingVertical:11},btnT:{fontSize:12.5,color:'#fff'}})
