import { Ionicons } from '@expo/vector-icons';
import { useLocalSearchParams, router } from 'expo-router';
import { Alert, ScrollView, StyleSheet, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useEffect, useMemo, useState } from 'react';
import { api } from '../src/api';
import { defaultPrefs, paletteFor, type LocalPrefs } from '../src/prefs';
import { getPrefs, getToken } from '../src/session';
import { NText } from '../src/ui';
const fa=new Intl.NumberFormat('fa-IR');const money=(n:any)=>`${fa.format(Number(n||0))} تومان`;

export default function Booking(){
  const p=useLocalSearchParams<{businessId:string;serviceId:string}>();const[b,setB]=useState<any>(null);const[service,setService]=useState<any>(null);const[staffId,setStaffId]=useState<number|0>(0);const[day,setDay]=useState('');const[slots,setSlots]=useState<any[]>([]);const[selected,setSelected]=useState<any>(null);const[busy,setBusy]=useState(false);const[prefs,setPrefs]=useState<LocalPrefs>(defaultPrefs);const t=paletteFor(prefs.audience,prefs.appearance);const s=useMemo(()=>styles(t),[prefs.audience,prefs.appearance]);const days=useMemo(()=>Array.from({length:5},(_,i)=>{const d=new Date();d.setDate(d.getDate()+i);return{key:d.toISOString().slice(0,10),label:i===0?'امروز':i===1?'فردا':new Intl.DateTimeFormat('fa-IR',{weekday:'long'}).format(d),date:new Intl.DateTimeFormat('fa-IR',{day:'numeric',month:'short'}).format(d)}}),[]);
  useEffect(()=>{setDay(days[0].key);getPrefs().then(x=>x&&setPrefs(x));api(`/v1/businesses/${p.businessId}`).then(j=>{setB(j.business);setService((j.business.services||[]).find((x:any)=>String(x.id)===String(p.serviceId))||j.business.services?.[0])}).catch(e=>Alert.alert('خطا',e.message))},[]);
  useEffect(()=>{if(!day||!service)return;setSelected(null);const staff=staffId?`&staff_id=${staffId}`:'';api(`/v1/businesses/${p.businessId}/availability?date=${day}&service_id=${service.id}${staff}`).then(j=>setSlots(j.slots||[])).catch(()=>setSlots([]))},[day,service?.id,staffId]);
  const confirm=async()=>{if(!selected)return Alert.alert('زمان را انتخاب کن');if(!(await getToken())){Alert.alert('ورود لازم است','برای ثبت نهایی با بله وارد شوید.',[{text:'ورود',onPress:()=>router.push('/login')},{text:'انصراف'}]);return}setBusy(true);try{const me=await api('/v1/me');if(!me.user?.phone_verified_at){Alert.alert('تأیید شماره لازم است','برای امنیت رزرو ابتدا شماره موبایل را در حساب تأیید کن.',[{text:'رفتن به حساب',onPress:()=>router.push('/profile')},{text:'انصراف'}]);return}const j=await api('/v1/bookings',{method:'POST',body:JSON.stringify({business_id:Number(p.businessId),service_id:Number(service.id),staff_id:selected.staff_id||staffId||null,starts_at:selected.starts_at,source:'APP',idempotency_key:`app-${Date.now()}-${p.businessId}-${service.id}`})});Alert.alert('رزرو ثبت شد',`کد رزرو: ${j.booking.reference}`,[{text:'مشاهده نوبت',onPress:()=>router.replace('/bookings')}])}catch(e:any){Alert.alert('ثبت نشد',e.message)}finally{setBusy(false)}};
  if(!b||!service)return <SafeAreaView edges={['bottom']} style={s.root}><NText style={s.loading}>در حال دریافت اطلاعات رزرو...</NText></SafeAreaView>;
  return <SafeAreaView edges={['bottom']} style={s.root}><ScrollView contentContainerStyle={s.wrap} showsVerticalScrollIndicator={false}>
    <View style={s.summary}><View style={s.summaryIcon}><Ionicons name="cut-outline" size={20} color={t.accent}/></View><View style={{flex:1}}><NText weight="semi" style={s.name}>{service.title}</NText><NText style={s.muted}>{b.name}</NText><NText weight="medium" style={s.price}>{money(service.price)} · {fa.format(service.duration_minutes)} دقیقه</NText></View></View>
    <Step n="۱" title="متخصص" t={t}/><View style={s.staffList}><TouchableOpacity activeOpacity={.72} style={[s.staff,staffId===0&&s.staffOn]} onPress={()=>setStaffId(0)}><Ionicons name={staffId===0?'radio-button-on':'radio-button-off'} size={18} color={staffId===0?t.accent:t.muted}/><NText weight="medium" style={s.staffT}>اولین متخصص آزاد</NText></TouchableOpacity>{(b.staff||[]).map((x:any)=><TouchableOpacity activeOpacity={.72} key={x.id} style={[s.staff,staffId===Number(x.id)&&s.staffOn]} onPress={()=>setStaffId(Number(x.id))}><Ionicons name={staffId===Number(x.id)?'radio-button-on':'radio-button-off'} size={18} color={staffId===Number(x.id)?t.accent:t.muted}/><NText weight="medium" style={s.staffT}>{x.name}</NText></TouchableOpacity>)}</View>
    <Step n="۲" title="روز" t={t}/><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.days}>{days.map(d=><TouchableOpacity activeOpacity={.72} key={d.key} style={[s.day,day===d.key&&s.dayOn]} onPress={()=>setDay(d.key)}><NText weight="semi" style={[s.dayTitle,day===d.key&&s.onT]}>{d.label}</NText><NText style={[s.daySub,day===d.key&&s.onT]}>{d.date}</NText></TouchableOpacity>)}</ScrollView>
    <Step n="۳" title="ساعت" t={t}/><View style={s.times}>{slots.map((slot:any)=>{const label=new Date(slot.starts_at).toLocaleTimeString('fa-IR',{hour:'2-digit',minute:'2-digit'});const on=selected?.starts_at===slot.starts_at&&selected?.staff_id===slot.staff_id;return <TouchableOpacity activeOpacity={.72} key={`${slot.starts_at}-${slot.staff_id}`} style={[s.time,on&&s.timeOn]} onPress={()=>setSelected(slot)}><NText weight="semi" style={[s.timeT,on&&s.onT]}>{label}</NText></TouchableOpacity>})}</View>{!slots.length?<View style={s.noSlot}><Ionicons name="time-outline" size={20} color={t.muted}/><NText style={s.muted}>در این روز زمان آزادی ثبت نشده است.</NText></View>:null}
    <View style={s.bill}><View style={s.billRow}><NText weight="semi" style={s.price}>{money(service.price)}</NText><NText style={s.muted}>مبلغ خدمت</NText></View><View style={s.billRow}><NText weight="semi" style={s.price}>{money(service.deposit_amount)}</NText><NText style={s.muted}>بیعانه</NText></View></View>
  </ScrollView><View style={s.ctaWrap}><TouchableOpacity disabled={busy||!selected} activeOpacity={.78} style={[s.cta,(!selected||busy)&&s.ctaOff]} onPress={confirm}><NText weight="bold" style={s.ctaT}>{busy?'در حال ثبت...':'ثبت نهایی رزرو'}</NText><Ionicons name="arrow-back" size={18} color="#fff"/></TouchableOpacity></View></SafeAreaView>
}
function Step({n,title,t}:any){return <View style={{flexDirection:'row-reverse',alignItems:'center',gap:7,marginTop:2}}><View style={{width:25,height:25,borderRadius:9,backgroundColor:t.accentSoft,alignItems:'center',justifyContent:'center'}}><NText weight="bold" style={{fontSize:11,color:t.accent}}>{n}</NText></View><NText weight="semi" style={{fontSize:15,color:t.text}}>{title}</NText></View>}
const styles=(t:any)=>StyleSheet.create({root:{flex:1,backgroundColor:t.bg},wrap:{padding:16,paddingBottom:98,gap:12},loading:{padding:22,textAlign:'center',color:t.muted},summary:{backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:18,padding:13,flexDirection:'row-reverse',alignItems:'center',gap:10},summaryIcon:{width:42,height:42,borderRadius:13,backgroundColor:t.accentSoft,alignItems:'center',justifyContent:'center'},name:{fontSize:15.5,textAlign:'right',color:t.text},muted:{fontSize:11.5,lineHeight:19,color:t.muted,textAlign:'right'},price:{fontSize:12,color:t.accent,textAlign:'right'},staffList:{gap:7},staff:{minHeight:46,backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:14,paddingHorizontal:12,flexDirection:'row-reverse',alignItems:'center',gap:8},staffOn:{borderColor:t.accent,backgroundColor:t.accentSoft},staffT:{fontSize:12.5,color:t.text},days:{gap:7},day:{minWidth:78,borderWidth:1,borderColor:t.line,backgroundColor:t.card,borderRadius:14,paddingHorizontal:11,paddingVertical:9,alignItems:'center'},dayOn:{backgroundColor:t.accent,borderColor:t.accent},dayTitle:{fontSize:11.5,color:t.text},daySub:{fontSize:9.5,color:t.muted,marginTop:2},onT:{color:'#fff'},times:{flexDirection:'row-reverse',flexWrap:'wrap',gap:7},time:{minWidth:'22%',backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:12,paddingVertical:10,alignItems:'center'},timeOn:{backgroundColor:t.accent,borderColor:t.accent},timeT:{fontSize:11.5,color:t.text},noSlot:{flexDirection:'row-reverse',alignItems:'center',gap:6,backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:14,padding:12},bill:{backgroundColor:t.card,borderRadius:16,borderWidth:1,borderColor:t.line,padding:13,gap:8,marginTop:3},billRow:{flexDirection:'row',justifyContent:'space-between'},ctaWrap:{position:'absolute',left:0,right:0,bottom:0,backgroundColor:t.card,borderTopWidth:StyleSheet.hairlineWidth,borderTopColor:t.line,paddingHorizontal:16,paddingTop:9,paddingBottom:10},cta:{height:48,borderRadius:15,backgroundColor:t.accent,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:7},ctaOff:{opacity:.45},ctaT:{fontSize:13.5,color:'#fff'}})
