import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useEffect, useMemo, useState } from 'react';
import { Alert, ScrollView, StyleSheet, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { api } from '../src/api';
import { jalaliDateTime } from '../src/dateFa';
import { effectiveAudience, paletteFor } from '../src/prefs';
import { getToken } from '../src/session';
import { usePrefs } from '../src/usePrefs';
import { BottomNav, NText, PageTitle } from '../src/ui';
const fa=new Intl.NumberFormat('fa-IR');const money=(n:any)=>`${fa.format(Number(n||0))} تومان`;
const statusFa=(x:string)=>({PENDING:'در انتظار',CONFIRMED:'تأیید شده',PAID:'پرداخت شده',COMPLETED:'انجام شده',CANCELLED:'لغو شده'} as any)[x]||x;
export default function Bookings(){const[rows,setRows]=useState<any[]>([]);const[loading,setLoading]=useState(true);const[logged,setLogged]=useState(false);const[prefs]=usePrefs();const audience=effectiveAudience(prefs);const t=paletteFor(audience,prefs.appearance);const s=useMemo(()=>styles(t),[audience,prefs.appearance]);const load=async()=>{const token=await getToken();setLogged(Boolean(token));if(!token){setLoading(false);return}try{const j=await api('/v1/me/bookings');setRows(j.items||[])}finally{setLoading(false)}};useEffect(()=>{load()},[]);const cancel=async(id:number)=>{try{await api(`/v1/bookings/${id}/cancel`,{method:'POST',body:JSON.stringify({reason:'لغو توسط کاربر در اپ'})});load()}catch(e:any){Alert.alert('لغو نشد',e.message)}};
return <SafeAreaView edges={['top']} style={s.root}><ScrollView contentContainerStyle={s.wrap} showsVerticalScrollIndicator={false}><PageTitle title="نوبت‌های من" sub="رزروهای پیش‌رو و سابقه خدمات"/>{loading?<NText style={s.muted}>در حال دریافت...</NText>:!logged?<View style={s.empty}><Ionicons name="log-in-outline" size={30} color={t.accent}/><NText weight="semi" style={s.emptyTitle}>برای دیدن نوبت‌ها وارد شوید</NText><TouchableOpacity style={s.btn} onPress={()=>router.push('/login')}><NText weight="bold" style={s.btnT}>ورود با بله</NText></TouchableOpacity></View>:!rows.length?<View style={s.empty}><Ionicons name="calendar-outline" size={32} color={t.muted}/><NText weight="semi" style={s.emptyTitle}>هنوز نوبتی ندارید</NText><NText style={s.muted}>خدمت موردنظرت را پیدا کن و زمان آزاد را انتخاب کن.</NText><TouchableOpacity style={s.btn} onPress={()=>router.replace('/search')}><NText weight="bold" style={s.btnT}>جستجوی خدمات</NText></TouchableOpacity></View>:rows.map(x=><View style={s.card} key={x.id}><View style={s.icon}><Ionicons name="calendar-outline" size={20} color={t.accent}/></View><View style={s.body}><View style={s.titleRow}><NText weight="medium" style={s.status}>{statusFa(x.status)}</NText><NText weight="semi" style={s.name}>{x.business_name}</NText></View><NText style={s.muted}>{x.staff_name?`متخصص: ${x.staff_name}`:'اولین متخصص آزاد'}</NText><NText weight="medium" style={s.date}>{jalaliDateTime(x.starts_at)}</NText><NText style={s.amount}>{money(x.total_amount)}</NText><View style={s.actions}>{['PENDING','CONFIRMED','PAID'].includes(x.status)?<TouchableOpacity activeOpacity={.7} style={s.cancel} onPress={()=>Alert.alert('لغو نوبت','این نوبت لغو شود؟',[{text:'خیر',style:'cancel'},{text:'بله',style:'destructive',onPress:()=>cancel(x.id)}])}><NText weight="medium" style={s.cancelT}>لغو نوبت</NText></TouchableOpacity>:null}{x.status==='COMPLETED'?<TouchableOpacity activeOpacity={.7} style={s.rate} onPress={()=>router.push({pathname:'/review',params:{bookingId:String(x.id),businessId:String(x.business_id),businessName:String(x.business_name)}})}><Ionicons name="star-outline" size={15} color={t.warning}/><NText weight="medium" style={s.rateT}>ثبت امتیاز و نظر</NText></TouchableOpacity>:null}</View></View></View>)}</ScrollView><BottomNav active="bookings" t={t}/></SafeAreaView>}
const styles=(t:any)=>StyleSheet.create({root:{flex:1,backgroundColor:t.bg},wrap:{paddingHorizontal:18,paddingTop:10,paddingBottom:24,gap:12},card:{flexDirection:'row-reverse',gap:10,backgroundColor:t.card,borderRadius:18,borderWidth:1,borderColor:t.line,padding:12},icon:{width:42,height:42,borderRadius:13,backgroundColor:t.accentSoft,alignItems:'center',justifyContent:'center'},body:{flex:1,gap:4},titleRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:8},name:{fontSize:14.5,textAlign:'right',color:t.text,flex:1},muted:{fontSize:11.5,lineHeight:18,color:t.muted,textAlign:'right'},date:{fontSize:12,color:t.text,textAlign:'right'},amount:{fontFamily:'Vazirmatn_500Medium',fontSize:11.5,color:t.accent,textAlign:'right'},status:{fontSize:9.5,color:t.success,backgroundColor:'#EAF5F0',paddingHorizontal:7,paddingVertical:3,borderRadius:8},cancel:{alignSelf:'flex-end',marginTop:4,paddingVertical:6,paddingHorizontal:9,borderRadius:10,borderWidth:1,borderColor:t.line},cancelT:{fontSize:10.5,color:t.danger},actions:{flexDirection:'row-reverse',gap:7,alignItems:'center',justifyContent:'flex-start',flexWrap:'wrap'},rate:{alignSelf:'flex-end',marginTop:4,paddingVertical:6,paddingHorizontal:9,borderRadius:10,borderWidth:1,borderColor:t.line,flexDirection:'row-reverse',alignItems:'center',gap:4},rateT:{fontSize:10.5,color:t.warning},empty:{backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:18,padding:24,alignItems:'center',gap:8},emptyTitle:{fontSize:15,color:t.text},btn:{marginTop:4,backgroundColor:t.accent,borderRadius:14,paddingHorizontal:18,paddingVertical:11},btnT:{fontSize:12.5,color:'#fff'}})
