import { useLocalSearchParams, router } from 'expo-router';
import { Alert, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useEffect, useMemo, useState } from 'react';
import { api } from '../src/api';
import { getPrefs, getToken } from '../src/session';
import { paletteFor, type Audience } from '../src/prefs';
const fa=new Intl.NumberFormat('fa-IR');const money=(n:any)=>`${fa.format(Number(n||0))} تومان`;
export default function Booking(){const p=useLocalSearchParams<{businessId:string;serviceId:string}>();const[b,setB]=useState<any>(null);const[service,setService]=useState<any>(null);const[staffId,setStaffId]=useState<number|0>(0);const[day,setDay]=useState('');const[slots,setSlots]=useState<any[]>([]);const[selected,setSelected]=useState<any>(null);const[busy,setBusy]=useState(false);const[audience,setAudience]=useState<Audience>('ALL');const t=paletteFor(audience);const s=useMemo(()=>styles(t),[audience]);const days=useMemo(()=>Array.from({length:5},(_,i)=>{const d=new Date();d.setDate(d.getDate()+i);return{key:d.toISOString().slice(0,10),label:i===0?'امروز':i===1?'فردا':new Intl.DateTimeFormat('fa-IR',{weekday:'long'}).format(d)}}),[]);
useEffect(()=>{setDay(days[0].key);getPrefs().then(x=>x&&setAudience(x.audience));api(`/v1/businesses/${p.businessId}`).then(j=>{setB(j.business);setService((j.business.services||[]).find((x:any)=>String(x.id)===String(p.serviceId))||j.business.services?.[0])}).catch(e=>Alert.alert('خطا',e.message))},[]);
useEffect(()=>{if(!day||!service)return;setSelected(null);const staff=staffId?`&staff_id=${staffId}`:'';api(`/v1/businesses/${p.businessId}/availability?date=${day}&service_id=${service.id}${staff}`).then(j=>setSlots(j.slots||[])).catch(()=>setSlots([]))},[day,service?.id,staffId]);
const confirm=async()=>{if(!selected)return Alert.alert('زمان را انتخاب کن');if(!(await getToken())){Alert.alert('ورود لازم است','برای ثبت نهایی با بله وارد شوید.',[{text:'ورود',onPress:()=>router.push('/login')},{text:'انصراف'}]);return}setBusy(true);try{const me=await api('/v1/me');if(!me.user?.phone_verified_at){Alert.alert('تأیید شماره لازم است','برای امنیت رزرو ابتدا شماره موبایل را در حساب تأیید کن.',[{text:'رفتن به حساب',onPress:()=>router.push('/profile')},{text:'انصراف'}]);return}const j=await api('/v1/bookings',{method:'POST',body:JSON.stringify({business_id:Number(p.businessId),service_id:Number(service.id),staff_id:selected.staff_id||staffId||null,starts_at:selected.starts_at,source:'APP',idempotency_key:`app-${Date.now()}-${p.businessId}-${service.id}`})});Alert.alert('رزرو ثبت شد',`کد رزرو: ${j.booking.reference}`, [{text:'نوبت‌های من',onPress:()=>router.replace('/bookings')}])}catch(e:any){if(e.code==='PHONE_VERIFICATION_REQUIRED')router.push('/profile');else Alert.alert('ثبت نشد',e.message)}finally{setBusy(false)}};
if(!b||!service)return <SafeAreaView edges={['bottom']} style={s.root}><Text style={s.loading}>در حال دریافت اطلاعات رزرو...</Text></SafeAreaView>;
return <SafeAreaView edges={['bottom']} style={s.root}><ScrollView contentContainerStyle={s.wrap}><View style={s.summary}><Text style={s.name}>{service.title}</Text><Text style={s.muted}>{b.name}</Text><Text style={s.price}>{money(service.price)} · {fa.format(service.duration_minutes)} دقیقه</Text>{Number(service.deposit_amount)>0&&<Text style={s.deposit}>بیعانه: {money(service.deposit_amount)}</Text>}</View><Text style={s.h}>۱. متخصص</Text><TouchableOpacity style={[s.staff,staffId===0&&s.onSoft]} onPress={()=>setStaffId(0)}><Text style={s.staffT}>اولین متخصص آزاد</Text><Text>{staffId===0?'●':'○'}</Text></TouchableOpacity>{(b.staff||[]).map((x:any)=><TouchableOpacity key={x.id} style={[s.staff,staffId===Number(x.id)&&s.onSoft]} onPress={()=>setStaffId(Number(x.id))}><Text style={s.staffT}>{x.name}</Text><Text>{staffId===Number(x.id)?'●':'○'}</Text></TouchableOpacity>)}<Text style={s.h}>۲. روز</Text><View style={s.row}>{days.map(d=><TouchableOpacity key={d.key} style={[s.choice,day===d.key&&s.on]} onPress={()=>setDay(d.key)}><Text style={[s.ct,day===d.key&&s.onT]}>{d.label}</Text></TouchableOpacity>)}</View><Text style={s.h}>۳. زمان آزاد واقعی</Text><View style={s.times}>{slots.map((slot:any)=>{const label=new Date(slot.starts_at).toLocaleTimeString('fa-IR',{hour:'2-digit',minute:'2-digit'});return <TouchableOpacity key={`${slot.starts_at}-${slot.staff_id}`} style={[s.time,selected?.starts_at===slot.starts_at&&selected?.staff_id===slot.staff_id&&s.on]} onPress={()=>setSelected(slot)}><Text style={[s.ct,selected===slot&&s.onT]}>{label}</Text></TouchableOpacity>})}</View>{!slots.length&&<Text style={s.muted}>در این روز زمان آزادی ثبت نشده است.</Text>}<View style={s.bill}><View style={s.billRow}><Text style={s.price}>{money(service.price)}</Text><Text style={s.muted}>مبلغ خدمت</Text></View><View style={s.billRow}><Text style={s.price}>{money(service.deposit_amount)}</Text><Text style={s.muted}>بیعانه</Text></View></View><TouchableOpacity disabled={busy} style={s.btn} onPress={confirm}><Text style={s.btnT}>{busy?'در حال ثبت...':'ثبت نهایی رزرو'}</Text></TouchableOpacity><Text style={s.note}>تداخل زمانی در سرور کنترل می‌شود؛ اگر همان لحظه زمان توسط شخص دیگری گرفته شود، رزرو رد می‌شود.</Text></ScrollView></SafeAreaView>}
const styles=(t:any)=>StyleSheet.create({root:{flex:1,backgroundColor:t.bg},wrap:{padding:18,paddingBottom:42,gap:14},loading:{padding:22,textAlign:'center',color:t.muted},summary:{backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:22,padding:16,gap:6},name:{fontSize:20,fontWeight:'900',textAlign:'right',color:t.text},muted:{color:t.muted,textAlign:'right',lineHeight:22},price:{color:t.accent,fontWeight:'900'},deposit:{textAlign:'right',color:t.warning,fontWeight:'800'},h:{fontSize:18,fontWeight:'900',textAlign:'right',marginTop:4,color:t.text},row:{flexDirection:'row-reverse',gap:8,flexWrap:'wrap'},choice:{borderWidth:1,borderColor:t.line,backgroundColor:t.card,borderRadius:14,paddingHorizontal:15,paddingVertical:11},ct:{fontWeight:'700',color:t.ink},on:{backgroundColor:t.accent,borderColor:t.accent},onT:{color:'#fff'},staff:{backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:17,padding:14,flexDirection:'row',justifyContent:'space-between'},onSoft:{borderColor:t.accent,backgroundColor:t.accentSoft},staffT:{fontWeight:'800',color:t.text},times:{flexDirection:'row-reverse',flexWrap:'wrap',gap:8},time:{minWidth:'29%',alignItems:'center',backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:14,padding:12},bill:{backgroundColor:t.card,borderRadius:18,borderWidth:1,borderColor:t.line,padding:15,gap:10},billRow:{flexDirection:'row',justifyContent:'space-between'},btn:{backgroundColor:t.accent,borderRadius:17,padding:16,alignItems:'center'},btnT:{color:'#fff',fontWeight:'900',fontSize:16},note:{fontSize:11,color:t.muted,textAlign:'center',lineHeight:19}})
