import { router } from 'expo-router';
import { useEffect, useMemo, useState } from 'react';
import { Alert, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { api } from '../src/api';
import { getPrefs, getToken } from '../src/session';
import { paletteFor, type Audience } from '../src/prefs';
const fa=new Intl.NumberFormat('fa-IR');const money=(n:any)=>`${fa.format(Number(n||0))} تومان`;
export default function Bookings(){const[rows,setRows]=useState<any[]>([]);const[loading,setLoading]=useState(true);const[audience,setAudience]=useState<Audience>('ALL');const t=paletteFor(audience);const s=useMemo(()=>styles(t),[audience]);const load=async()=>{const p=await getPrefs();if(p)setAudience(p.audience);if(!(await getToken())){setLoading(false);return}try{const j=await api('/v1/me/bookings');setRows(j.items||[])}catch(e:any){if(e.status===401)Alert.alert('ورود لازم است')}finally{setLoading(false)}};useEffect(()=>{load()},[]);const cancel=async(id:number)=>{try{await api(`/v1/bookings/${id}/cancel`,{method:'POST',body:JSON.stringify({reason:'لغو توسط کاربر در اپ'})});load()}catch(e:any){Alert.alert('لغو نشد',e.message)}};
return <SafeAreaView edges={['bottom']} style={s.root}><ScrollView contentContainerStyle={s.wrap}>{loading?<Text style={s.muted}>در حال دریافت...</Text>:!rows.length?<View style={s.empty}><Text style={s.h}>هنوز نوبتی ندارید</Text><TouchableOpacity style={s.btn} onPress={()=>router.push('/search')}><Text style={s.btnT}>جستجوی خدمات</Text></TouchableOpacity></View>:rows.map(x=><View style={s.card} key={x.id}><View style={s.icon}><Text>✦</Text></View><View style={{flex:1,gap:6}}><Text style={s.name}>{x.business_name}</Text><Text style={s.muted}>{x.staff_name?`متخصص: ${x.staff_name}`:'اولین متخصص آزاد'}</Text><Text style={s.date}>{new Date(String(x.starts_at).replace(' ','T')).toLocaleString('fa-IR')}</Text><Text style={s.status}>{x.status}</Text><Text style={s.muted}>{money(x.total_amount)}</Text>{['PENDING','CONFIRMED','PAID'].includes(x.status)&&<TouchableOpacity style={s.ghost} onPress={()=>Alert.alert('لغو نوبت','این نوبت لغو شود؟',[{text:'خیر'},{text:'بله',style:'destructive',onPress:()=>cancel(x.id)}])}><Text style={s.ghostT}>لغو نوبت</Text></TouchableOpacity>}</View></View>)}</ScrollView></SafeAreaView>}
const styles=(t:any)=>StyleSheet.create({root:{flex:1,backgroundColor:t.bg},wrap:{padding:18,paddingBottom:40,gap:14},card:{flexDirection:'row-reverse',gap:12,backgroundColor:t.card,borderRadius:22,borderWidth:1,borderColor:t.line,padding:15},icon:{width:52,height:52,borderRadius:16,backgroundColor:t.accentSoft,alignItems:'center',justifyContent:'center'},name:{fontSize:17,fontWeight:'900',textAlign:'right',color:t.text},muted:{color:t.muted,textAlign:'right',lineHeight:21},date:{fontWeight:'800',textAlign:'right',color:t.text},status:{alignSelf:'flex-end',color:t.success,backgroundColor:'#EAF7F0',paddingHorizontal:8,paddingVertical:5,borderRadius:10,fontSize:11,fontWeight:'800'},ghost:{borderWidth:1,borderColor:t.line,borderRadius:12,paddingHorizontal:11,paddingVertical:9,alignSelf:'flex-end'},ghostT:{color:t.accent,fontWeight:'800',fontSize:12},empty:{backgroundColor:t.card,borderRadius:22,padding:22,gap:14},h:{fontSize:18,fontWeight:'900',textAlign:'right',color:t.text},btn:{backgroundColor:t.accent,borderRadius:15,padding:14,alignItems:'center'},btnT:{color:'#fff',fontWeight:'900'}})
