import { Ionicons } from '@expo/vector-icons';
import { useLocalSearchParams, router } from 'expo-router';
import { Alert, ScrollView, StyleSheet, TouchableOpacity, View } from 'react-native';
import { SafeAreaView, useSafeAreaInsets } from 'react-native-safe-area-context';
import { useEffect, useMemo, useState } from 'react';
import { api } from '../src/api';
import { bookingDays, faTime } from '../src/dateFa';
import { defaultPrefs, effectiveAudience, genderAllows, paletteFor, type LocalPrefs } from '../src/prefs';
import { getPrefs, getToken } from '../src/session';
import { NText, SupportButton } from '../src/ui';
const fa=new Intl.NumberFormat('fa-IR');const money=(n:any)=>`${fa.format(Number(n||0))} تومان`;

export default function Booking(){
  const p=useLocalSearchParams<{businessId:string;serviceId:string}>();const insets=useSafeAreaInsets();const[b,setB]=useState<any>(null);const[selectedIds,setSelectedIds]=useState<number[]>([]);const[staffId,setStaffId]=useState<number|0>(0);const[day,setDay]=useState('');const[slots,setSlots]=useState<any[]>([]);const[selected,setSelected]=useState<any>(null);const[busy,setBusy]=useState(false);const[availabilityReason,setAvailabilityReason]=useState('');const[prefs,setPrefs]=useState<LocalPrefs>(defaultPrefs);const audience=effectiveAudience(prefs);const t=paletteFor(audience,prefs.appearance);const s=useMemo(()=>styles(t),[audience,prefs.appearance]);const days=useMemo(()=>bookingDays(7),[]);
  useEffect(()=>{setDay(days[0].key);(async()=>{const pp=(await getPrefs())||defaultPrefs;setPrefs(pp);try{const j=await api(`/v1/businesses/${p.businessId}`);setB(j.business);const a=effectiveAudience(pp);const requested=Number(p.serviceId||0);const active=(j.business.services||[]).filter((x:any)=>genderAllows(x.gender,a)&&Number(x.bookable_staff_count||0)>0);const initial=active.find((x:any)=>Number(x.id)===requested)||active[0];setSelectedIds(initial?[Number(initial.id)]:[])}catch(e:any){Alert.alert('خطا',e.message)}})()},[]);
  const services=useMemo(()=>(b?.services||[]).filter((x:any)=>genderAllows(x.gender,audience)),[b,audience]);
  const selectedServices=useMemo(()=>services.filter((x:any)=>selectedIds.includes(Number(x.id))),[services,selectedIds]);
  const eligibleStaff=useMemo(()=>{if(!b||!selectedIds.length)return[];return (b.staff||[]).filter((st:any)=>{const ids=(st.service_ids||[]).map(Number);return selectedIds.every(id=>ids.includes(id))})},[b,selectedIds]);
  const totalPrice=selectedServices.reduce((n:number,x:any)=>n+Number(x.price||0),0);const totalDeposit=selectedServices.reduce((n:number,x:any)=>n+Number(x.deposit_amount||0),0);const totalDuration=selectedServices.reduce((n:number,x:any)=>n+Number(x.duration_minutes||0),0);
  useEffect(()=>{setSelectedIds(v=>v.filter(id=>services.some((x:any)=>Number(x.id)===id)));if(staffId&&!eligibleStaff.some((x:any)=>Number(x.id)===staffId))setStaffId(0);setSelected(null)},[audience,eligibleStaff.length]);
  useEffect(()=>{if(!day||!selectedIds.length||!eligibleStaff.length){setSlots([]);setAvailabilityReason(eligibleStaff.length?'':'برای این ترکیب خدمات متخصص مشترک فعالی وجود ندارد.');return}setSelected(null);const staff=staffId?`&staff_id=${staffId}`:'';api(`/v1/businesses/${p.businessId}/availability?date=${day}&service_ids=${selectedIds.join(',')}${staff}`).then(j=>{setSlots(j.slots||[]);setAvailabilityReason(j.bookable===false?(j.reason||'این ترکیب قابل رزرو نیست.'):'')}).catch(e=>{setSlots([]);setAvailabilityReason(e.message||'زمان آزاد دریافت نشد.')})},[day,selectedIds.join(','),staffId,eligibleStaff.length]);
  const toggleService=(id:number)=>{if(!services.some((x:any)=>Number(x.id)===id))return Alert.alert('این خدمت برای حساب شما قابل انتخاب نیست');const isOn=selectedIds.includes(id);if(isOn&&selectedIds.length===1)return Alert.alert('حداقل یک خدمت لازم است');setSelectedIds(v=>isOn?v.filter(x=>x!==id):[...v,id]);};
  const confirm=async()=>{if(!selectedIds.length)return Alert.alert('خدمت را انتخاب کن');if(selectedServices.length!==selectedIds.length)return Alert.alert('خدمت نامعتبر','یکی از خدمات با جنسیت حساب شما سازگار نیست.');if(!eligibleStaff.length)return Alert.alert('متخصص مشترک وجود ندارد','این خدمات را جداگانه رزرو کن یا ترکیب دیگری انتخاب کن.');if(!selected)return Alert.alert('زمان را انتخاب کن');if(!(await getToken())){Alert.alert('ورود لازم است','برای ثبت نهایی با بله وارد شوید.',[{text:'ورود',onPress:()=>router.push('/login')},{text:'انصراف'}]);return}setBusy(true);try{const me=await api('/v1/me');if(!me.user?.phone_verified_at){Alert.alert('تأیید شماره لازم است','برای امنیت رزرو ابتدا شماره موبایل را در حساب تأیید کن.',[{text:'رفتن به حساب',onPress:()=>router.push('/profile')},{text:'انصراف'}]);return}const accountGender=me.user?.profile_gender;if((accountGender==='FEMALE'||accountGender==='MALE')&&accountGender!==audience)return Alert.alert('تنظیمات حساب تغییر کرده','نوع خدمات با جنسیت فعلی حساب سازگار نیست. صفحه را دوباره باز کن.');const j=await api('/v1/bookings',{method:'POST',body:JSON.stringify({business_id:Number(p.businessId),service_ids:selectedIds,staff_id:selected.staff_id||staffId||null,starts_at:selected.starts_at,source:'APP',idempotency_key:`app-${Date.now()}-${p.businessId}-${[...selectedIds].sort((a,b)=>a-b).join('-')}`})});Alert.alert('رزرو ثبت شد',`کد رزرو: ${j.booking.reference}`,[{text:'مشاهده نوبت',onPress:()=>router.replace('/bookings')}])}catch(e:any){Alert.alert('ثبت نشد',e.message)}finally{setBusy(false)}};
  if(!b)return <SafeAreaView edges={['bottom']} style={s.root}><NText style={s.loading}>در حال دریافت اطلاعات رزرو...</NText></SafeAreaView>;
  if(!services.some((x:any)=>Number(x.bookable_staff_count||0)>0))return <SafeAreaView edges={['bottom']} style={s.root}><View style={s.blocked}><Ionicons name="person-remove-outline" size={28} color={t.warning}/><NText weight="semi" style={s.blockedTitle}>نوبت‌گیری برای این حساب فعال نیست</NText><NText style={s.muted}>خدمت قابل رزروی متناسب با جنسیت حساب شما در این مجموعه وجود ندارد.</NText></View></SafeAreaView>;
  return <SafeAreaView edges={[]} style={s.root}><ScrollView contentContainerStyle={[s.wrap,{paddingBottom:88+insets.bottom}]} showsVerticalScrollIndicator={false}>
    <View style={s.topAction}><SupportButton t={t} label/><NText style={s.topHint}>رزرو فقط از خدمات سازگار با حساب شما</NText></View>
    <View style={s.summary}><View style={s.summaryIcon}><Ionicons name="calendar-outline" size={20} color={t.accent}/></View><View style={{flex:1}}><NText weight="semi" style={s.name}>{b.name}</NText><NText style={s.muted}>{fa.format(selectedServices.length)} خدمت · {fa.format(totalDuration)} دقیقه</NText><NText weight="medium" style={s.price}>{money(totalPrice)}</NText></View></View>
    <Step n="۱" title="خدمات" t={t}/><View style={s.serviceList}>{services.map((sv:any)=>{const id=Number(sv.id);const on=selectedIds.includes(id);const enabled=Number(sv.bookable_staff_count||0)>0;return <TouchableOpacity disabled={!enabled} activeOpacity={.72} key={id} style={[s.service,on&&s.serviceOn,!enabled&&s.serviceOff]} onPress={()=>toggleService(id)}><Ionicons name={on?'checkbox':'square-outline'} size={19} color={!enabled?t.muted:on?t.accent:t.muted}/><View style={{flex:1}}><NText weight="medium" style={s.serviceName}>{sv.title}</NText><NText style={s.muted}>{money(sv.price)} · {fa.format(Number(sv.duration_minutes||0))} دقیقه{!enabled?' · بدون متخصص':''}</NText></View></TouchableOpacity>})}</View>
    <Step n="۲" title="متخصص" t={t}/>{eligibleStaff.length?<View style={s.staffList}><TouchableOpacity activeOpacity={.72} style={[s.staff,staffId===0&&s.staffOn]} onPress={()=>setStaffId(0)}><Ionicons name={staffId===0?'radio-button-on':'radio-button-off'} size={18} color={staffId===0?t.accent:t.muted}/><NText weight="medium" style={s.staffT}>اولین متخصص آزاد برای همه خدمات</NText></TouchableOpacity>{eligibleStaff.map((x:any)=><TouchableOpacity activeOpacity={.72} key={x.id} style={[s.staff,staffId===Number(x.id)&&s.staffOn]} onPress={()=>setStaffId(Number(x.id))}><Ionicons name={staffId===Number(x.id)?'radio-button-on':'radio-button-off'} size={18} color={staffId===Number(x.id)?t.accent:t.muted}/><NText weight="medium" style={s.staffT}>{x.name}</NText></TouchableOpacity>)}</View>:<View style={s.noSlot}><Ionicons name="alert-circle-outline" size={20} color={t.warning}/><NText style={s.muted}>یک متخصص مشترک برای تمام خدمات انتخاب‌شده وجود ندارد؛ یک خدمت را حذف کن یا خدمات را جداگانه رزرو کن.</NText></View>}
    <Step n="۳" title="روز (تقویم شمسی)" t={t}/><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.days}>{days.map(d=><TouchableOpacity activeOpacity={.72} key={d.key} style={[s.day,day===d.key&&s.dayOn]} onPress={()=>setDay(d.key)}><NText weight="semi" style={[s.dayTitle,day===d.key&&s.onT]}>{d.label}</NText><NText style={[s.daySub,day===d.key&&s.onT]}>{d.date}</NText></TouchableOpacity>)}</ScrollView>
    <Step n="۴" title="ساعت" t={t}/><View style={s.times}>{slots.map((slot:any)=>{const label=faTime(slot.starts_at);const on=selected?.starts_at===slot.starts_at&&selected?.staff_id===slot.staff_id;return <TouchableOpacity activeOpacity={.72} key={`${slot.starts_at}-${slot.staff_id}`} style={[s.time,on&&s.timeOn]} onPress={()=>setSelected(slot)}><NText weight="semi" style={[s.timeT,on&&s.onT]}>{label}</NText></TouchableOpacity>})}</View>{!slots.length?<View style={s.noSlot}><Ionicons name="time-outline" size={20} color={t.muted}/><NText style={s.muted}>{availabilityReason||'در این روز زمان آزادی ثبت نشده است.'}</NText></View>:null}
    <View style={s.bill}><View style={s.billRow}><NText weight="semi" style={s.price}>{money(totalPrice)}</NText><NText style={s.muted}>مجموع خدمات</NText></View><View style={s.billRow}><NText weight="semi" style={s.price}>{money(totalDeposit)}</NText><NText style={s.muted}>مجموع بیعانه</NText></View><View style={s.billRow}><NText weight="semi" style={s.price}>{fa.format(totalDuration)} دقیقه</NText><NText style={s.muted}>زمان کل</NText></View></View>
  </ScrollView><View style={[s.ctaWrap,{paddingBottom:10+insets.bottom}]}><TouchableOpacity disabled={busy||!selected||!eligibleStaff.length} activeOpacity={.78} style={[s.cta,(!selected||busy||!eligibleStaff.length)&&s.ctaOff]} onPress={confirm}><NText weight="bold" style={s.ctaT}>{busy?'در حال ثبت...':'تأیید نهایی رزرو'}</NText><Ionicons name="arrow-back" size={18} color="#fff"/></TouchableOpacity></View></SafeAreaView>
}
function Step({n,title,t}:any){return <View style={{flexDirection:'row-reverse',alignItems:'center',gap:7,marginTop:2}}><View style={{width:25,height:25,borderRadius:9,backgroundColor:t.accentSoft,alignItems:'center',justifyContent:'center'}}><NText weight="bold" style={{fontSize:11,color:t.accent}}>{n}</NText></View><NText weight="semi" style={{fontSize:15,color:t.text}}>{title}</NText></View>}
const styles=(t:any)=>StyleSheet.create({root:{flex:1,backgroundColor:t.bg},wrap:{padding:16,gap:12},loading:{padding:22,textAlign:'center',color:t.muted},blocked:{margin:18,backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:18,padding:22,alignItems:'center',gap:8},blockedTitle:{fontSize:16,color:t.text},topAction:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},topHint:{fontSize:10.5,color:t.muted,textAlign:'right'},summary:{backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:18,padding:13,flexDirection:'row-reverse',alignItems:'center',gap:10},summaryIcon:{width:42,height:42,borderRadius:13,backgroundColor:t.accentSoft,alignItems:'center',justifyContent:'center'},name:{fontSize:15.5,textAlign:'right',color:t.text},muted:{fontSize:11.5,lineHeight:19,color:t.muted,textAlign:'right'},price:{fontSize:12,color:t.accent,textAlign:'right'},serviceList:{gap:7},service:{minHeight:50,backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:14,padding:11,flexDirection:'row-reverse',alignItems:'center',gap:8},serviceOn:{borderColor:t.accent,backgroundColor:t.accentSoft},serviceOff:{opacity:.5},serviceName:{fontSize:12.8,color:t.text,textAlign:'right'},staffList:{gap:7},staff:{minHeight:46,backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:14,paddingHorizontal:12,flexDirection:'row-reverse',alignItems:'center',gap:8},staffOn:{borderColor:t.accent,backgroundColor:t.accentSoft},staffT:{fontSize:12.5,color:t.text},days:{gap:7,flexDirection:'row-reverse'},day:{minWidth:78,borderWidth:1,borderColor:t.line,backgroundColor:t.card,borderRadius:14,paddingHorizontal:11,paddingVertical:9,alignItems:'center'},dayOn:{backgroundColor:t.accent,borderColor:t.accent},dayTitle:{fontSize:11.5,color:t.text},daySub:{fontSize:9.5,color:t.muted,marginTop:2},onT:{color:'#fff'},times:{flexDirection:'row-reverse',flexWrap:'wrap',gap:7},time:{minWidth:'22%',backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:12,paddingVertical:10,alignItems:'center'},timeOn:{backgroundColor:t.accent,borderColor:t.accent},timeT:{fontSize:11.5,color:t.text},noSlot:{flexDirection:'row-reverse',alignItems:'center',gap:6,backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:14,padding:12},bill:{backgroundColor:t.card,borderRadius:16,borderWidth:1,borderColor:t.line,padding:13,gap:8,marginTop:3},billRow:{flexDirection:'row',justifyContent:'space-between'},ctaWrap:{position:'absolute',left:0,right:0,bottom:0,backgroundColor:t.card,borderTopWidth:StyleSheet.hairlineWidth,borderTopColor:t.line,paddingHorizontal:16,paddingTop:9},cta:{height:48,borderRadius:15,backgroundColor:t.accent,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:7},ctaOff:{opacity:.45},ctaT:{fontSize:13.5,color:'#fff'}})
