import { Ionicons } from '@expo/vector-icons';
import { router, useFocusEffect } from 'expo-router';
import { useCallback, useMemo, useState } from 'react';
import { ScrollView, StyleSheet, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { api } from '../src/api';
import { defaultPrefs, paletteFor, type LocalPrefs } from '../src/prefs';
import { getPrefs } from '../src/session';
import { NText } from '../src/ui';
export default function Dashboard(){const[items,setItems]=useState<any[]>([]);const[prefs,setPrefs]=useState<LocalPrefs>(defaultPrefs);const t=paletteFor(prefs.audience,prefs.appearance);const s=useMemo(()=>styles(t),[prefs.audience,prefs.appearance]);const load=useCallback(()=>{getPrefs().then(p=>p&&setPrefs(p));api('/v1/me/businesses').then(j=>setItems(j.items||[])).catch(()=>setItems([]))},[]);useFocusEffect(load);return <SafeAreaView edges={['bottom']} style={s.root}><ScrollView contentContainerStyle={s.wrap} showsVerticalScrollIndicator={false}><View><NText weight="bold" style={s.h1}>کسب‌وکارهای من</NText><NText style={s.muted}>سالن، آرایشگاه، کلینیک یا پروفایل متخصص مستقل را مدیریت کن.</NText></View>{items.length?items.map(x=><View key={x.id} style={s.card}><View style={s.row}><NText weight="medium" style={[s.status,x.status==='APPROVED'&&s.approved]}>{x.status==='APPROVED'?'تأییدشده':x.status==='REJECTED'?'ردشده':'در انتظار بررسی'}</NText><NText weight="semi" style={s.name}>{x.name}</NText></View><NText style={s.muted}>{[x.province,x.city].filter(Boolean).join('، ')} · {x.gender==='MALE'?'آقایان':x.gender==='FEMALE'?'بانوان':'هر دو'}</NText><TouchableOpacity activeOpacity={.72} style={s.outline} onPress={()=>router.push({pathname:'/business-register',params:{businessId:String(x.id)}})}><Ionicons name="settings-outline" size={17} color={t.accent}/><NText weight="semi" style={s.outlineT}>مدیریت متخصص‌ها و خدمات</NText></TouchableOpacity></View>):<View style={s.empty}><Ionicons name="storefront-outline" size={32} color={t.muted}/><NText weight="semi" style={s.name}>هنوز کسب‌وکاری ثبت نکرده‌اید</NText><NText style={s.muted}>ثبت اولیه چند دقیقه زمان می‌برد و بعد از بررسی منتشر می‌شود.</NText></View>}<TouchableOpacity activeOpacity={.75} style={s.btn} onPress={()=>router.push('/business-register')}><Ionicons name="add-circle-outline" size={19} color="#fff"/><NText weight="bold" style={s.btnT}>ثبت کسب‌وکار جدید</NText></TouchableOpacity><View style={s.info}><Ionicons name="calendar-outline" size={20} color={t.accent}/><View style={{flex:1}}><NText weight="semi" style={s.infoT}>قاعده نوبت‌گیری</NText><NText style={s.muted}>هر خدمت فقط زمانی قابل رزرو است که حداقل یک متخصص فعال به آن متصل باشد و در بازه انتخابی زمان آزاد داشته باشد.</NText></View></View></ScrollView></SafeAreaView>}
const styles=(t:any)=>StyleSheet.create({root:{flex:1,backgroundColor:t.bg},wrap:{padding:16,paddingBottom:34,gap:12},h1:{fontSize:22,lineHeight:33,textAlign:'right',color:t.text},muted:{fontSize:11.5,lineHeight:19,color:t.muted,textAlign:'right'},card:{backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:17,padding:13,gap:8},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:8},name:{fontSize:14.5,textAlign:'right',color:t.text,flex:1},status:{fontSize:9.5,backgroundColor:'#FFF3E5',color:'#925D15',paddingHorizontal:7,paddingVertical:4,borderRadius:8},approved:{backgroundColor:'#EAF6F0',color:t.success},outline:{height:42,borderWidth:1,borderColor:t.line,borderRadius:13,paddingHorizontal:11,flexDirection:'row-reverse',alignItems:'center',justifyContent:'center',gap:6},outlineT:{fontSize:11.5,color:t.accent},btn:{height:47,backgroundColor:t.accent,borderRadius:14,flexDirection:'row-reverse',alignItems:'center',justifyContent:'center',gap:7},btnT:{fontSize:12.5,color:'#fff'},info:{backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:17,padding:13,flexDirection:'row-reverse',gap:10,alignItems:'flex-start'},infoT:{fontSize:13.5,color:t.text,textAlign:'right',marginBottom:3},empty:{backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:17,padding:20,alignItems:'center',gap:7}})
