import { router } from 'expo-router';
import { useEffect, useMemo, useState } from 'react';
import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { api } from '../src/api';
import { getPrefs } from '../src/session';
import { paletteFor, type Audience } from '../src/prefs';
export default function Dashboard(){const[items,setItems]=useState<any[]>([]);const[audience,setAudience]=useState<Audience>('ALL');const t=paletteFor(audience);const s=useMemo(()=>styles(t),[audience]);useEffect(()=>{getPrefs().then(p=>p&&setAudience(p.audience));api('/v1/me/businesses').then(j=>setItems(j.items||[])).catch(()=>setItems([]))},[]);return <SafeAreaView edges={['bottom']} style={s.root}><ScrollView contentContainerStyle={s.wrap}><View><Text style={s.kicker}>مدیریت حرفه‌ای</Text><Text style={s.h1}>کسب‌وکارهای من</Text><Text style={s.muted}>سالن، آرایشگر، خدمات، پرسنل، شیفت و تجهیزات را از یک مسیر مدیریت کن.</Text></View>{items.length?items.map(x=><View key={x.id} style={s.card}><View style={s.row}><Text style={[s.status,x.status==='APPROVED'&&s.approved]}>{x.status}</Text><Text style={s.name}>{x.name}</Text></View><Text style={s.muted}>{x.city||''} · {x.gender==='MALE'?'آقایان':x.gender==='FEMALE'?'بانوان':'هر دو'}</Text><TouchableOpacity style={s.outline} onPress={()=>router.push('/business-register')}><Text style={s.outlineT}>افزودن اطلاعات / خدمت / پرسنل</Text></TouchableOpacity></View>):<View style={s.card}><Text style={s.name}>هنوز کسب‌وکاری ثبت نکرده‌اید</Text><Text style={s.muted}>ثبت اولیه چند دقیقه زمان می‌برد و پس از بررسی مدیریت منتشر می‌شود.</Text></View>}<TouchableOpacity style={s.btn} onPress={()=>router.push('/business-register')}><Text style={s.btnT}>ثبت کسب‌وکار جدید</Text></TouchableOpacity><View style={s.ai}><Text style={s.aiT}>منطق زمان‌بندی نوبین</Text><Text style={s.muted}>هر خدمت مدت مشخص دارد؛ زمان آزاد بر اساس شیفت پرسنل محاسبه می‌شود و ساختار منابع برای صندلی، اتاق، تخت یا دستگاه نیز در Backend اضافه شده است.</Text></View></ScrollView></SafeAreaView>}
const styles=(t:any)=>StyleSheet.create({root:{flex:1,backgroundColor:t.bg},wrap:{padding:18,paddingBottom:40,gap:15},kicker:{textAlign:'right',color:t.accent,fontWeight:'800'},h1:{fontSize:26,fontWeight:'900',textAlign:'right',color:t.text},muted:{color:t.muted,textAlign:'right',lineHeight:22},card:{backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:20,padding:16,gap:10},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},name:{fontSize:17,fontWeight:'900',textAlign:'right',color:t.text},status:{fontSize:11,fontWeight:'900',backgroundColor:'#FFF2E5',color:'#9A5B12',paddingHorizontal:8,paddingVertical:5,borderRadius:9},approved:{backgroundColor:'#E8F7EF',color:t.success},outline:{borderWidth:1,borderColor:t.line,borderRadius:14,padding:12,alignItems:'center'},outlineT:{color:t.accent,fontWeight:'800'},btn:{backgroundColor:t.accent,borderRadius:16,padding:15,alignItems:'center'},btnT:{color:'#fff',fontWeight:'900'},ai:{backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:20,padding:16,gap:7},aiT:{textAlign:'right',fontSize:16,fontWeight:'900',color:t.accent}})
