import { useState } from 'react';
import { Alert, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { api } from '../src/api';
import { paletteFor } from '../src/prefs';

export default function BusinessRegister(){const t=paletteFor('ALL');const s=styles(t);const[businessId,setBusinessId]=useState<number|null>(null);const[name,setName]=useState('');const[city,setCity]=useState('');const[address,setAddress]=useState('');const[type,setType]=useState('SALON');const[gender,setGender]=useState('ALL');const[staff,setStaff]=useState('');const[service,setService]=useState('');const[price,setPrice]=useState('');const[duration,setDuration]=useState('60');const[resource,setResource]=useState('');
const create=async()=>{try{const j=await api('/v1/businesses/register',{method:'POST',body:JSON.stringify({name,city,address,type,gender})});setBusinessId(Number(j.business.id));Alert.alert('ثبت شد','کسب‌وکار برای بررسی مدیر ثبت شد. حالا می‌توانی پرسنل و خدمات را تکمیل کنی.')}catch(e:any){Alert.alert('ثبت ناموفق',e.message)}};
const addStaff=async()=>{if(!businessId)return;try{await api(`/v1/businesses/${businessId}/staff`,{method:'POST',body:JSON.stringify({name:staff,gender:gender==='ALL'?'UNSPECIFIED':gender})});setStaff('');Alert.alert('انجام شد','پرسنل اضافه شد.')}catch(e:any){Alert.alert('خطا',e.message)}};
const addService=async()=>{if(!businessId)return;try{await api(`/v1/businesses/${businessId}/services`,{method:'POST',body:JSON.stringify({title:service,price:Number(price||0),duration_minutes:Number(duration||30),gender})});setService('');setPrice('');Alert.alert('انجام شد','خدمت اضافه شد.')}catch(e:any){Alert.alert('خطا',e.message)}};
const addResource=async()=>{if(!businessId)return;try{await api(`/v1/businesses/${businessId}/resources`,{method:'POST',body:JSON.stringify({name:resource,type:'OTHER',capacity:1})});setResource('');Alert.alert('انجام شد','منبع/تجهیزات اضافه شد.')}catch(e:any){Alert.alert('خطا',e.message)}};
const addHours=async()=>{if(!businessId)return;try{for(let w=0;w<7;w++)await api(`/v1/businesses/${businessId}/shifts`,{method:'POST',body:JSON.stringify({weekday:w,start_time:'09:00',end_time:'20:00'})});Alert.alert('انجام شد','ساعت کاری اولیه ۹ تا ۲۰ برای همه روزها ثبت شد؛ بعداً قابل ویرایش است.')}catch(e:any){Alert.alert('خطا',e.message)}};
return <SafeAreaView edges={['bottom']} style={s.root}><ScrollView contentContainerStyle={s.wrap} keyboardShouldPersistTaps="handled"><Text style={s.h1}>راه‌اندازی کسب‌وکار</Text><Text style={s.p}>سالن، آرایشگاه، کلینیک یا ارائه‌دهنده مستقل را ثبت کن. بعد از تأیید مدیریت در جستجوی عمومی نمایش داده می‌شود.</Text>{!businessId?<><Field label="نام کسب‌وکار" value={name} set={setName}/><Field label="شهر" value={city} set={setCity}/><Field label="آدرس" value={address} set={setAddress}/><Text style={s.label}>نوع</Text><View style={s.row}>{[['SALON','سالن/آرایشگاه'],['CLINIC','کلینیک'],['FREELANCER','مستقل']].map(([v,l])=><Chip key={v} on={type===v} label={l} press={()=>setType(v)} t={t}/>)}</View><Text style={s.label}>مخاطب خدمات</Text><View style={s.row}>{[['FEMALE','بانوان'],['MALE','آقایان'],['ALL','هر دو']].map(([v,l])=><Chip key={v} on={gender===v} label={l} press={()=>setGender(v)} t={t}/>)}</View><TouchableOpacity style={s.btn} onPress={create}><Text style={s.btnT}>ثبت و ادامه</Text></TouchableOpacity></>:<><View style={s.success}><Text style={s.successT}>کسب‌وکار #{businessId} ثبت شده و در انتظار بررسی است.</Text></View><Text style={s.h2}>پرسنل / آرایشگر</Text><Field label="نام پرسنل" value={staff} set={setStaff}/><TouchableOpacity style={s.outline} onPress={addStaff}><Text style={s.outlineT}>افزودن پرسنل</Text></TouchableOpacity><Text style={s.h2}>خدمت</Text><Field label="عنوان خدمت" value={service} set={setService}/><View style={s.two}><Field label="قیمت (تومان)" value={price} set={setPrice} numeric/><Field label="مدت (دقیقه)" value={duration} set={setDuration} numeric/></View><TouchableOpacity style={s.outline} onPress={addService}><Text style={s.outlineT}>افزودن خدمت</Text></TouchableOpacity><Text style={s.h2}>صندلی / اتاق / دستگاه</Text><Field label="نام منبع" value={resource} set={setResource}/><TouchableOpacity style={s.outline} onPress={addResource}><Text style={s.outlineT}>افزودن منبع</Text></TouchableOpacity><Text style={s.h2}>ساعات کاری اولیه</Text><TouchableOpacity style={s.outline} onPress={addHours}><Text style={s.outlineT}>ثبت ۰۹:۰۰ تا ۲۰:۰۰ برای همه روزها</Text></TouchableOpacity></>}</ScrollView></SafeAreaView>}
function Field({label,value,set,numeric=false}:any){return <View style={{gap:6}}><Text style={{textAlign:'right',fontWeight:'800'}}>{label}</Text><TextInput value={value} onChangeText={set} keyboardType={numeric?'number-pad':'default'} textAlign="right" style={{backgroundColor:'#fff',borderWidth:1,borderColor:'#DCE6E3',borderRadius:15,padding:13}}/></View>}
function Chip({on,label,press,t}:any){return <TouchableOpacity onPress={press} style={{borderWidth:1,borderColor:on?t.accent:t.line,backgroundColor:on?t.accentSoft:'#fff',borderRadius:14,paddingHorizontal:12,paddingVertical:10}}><Text style={{color:on?t.accent:t.text,fontWeight:'800'}}>{label}</Text></TouchableOpacity>}
const styles=(t:any)=>StyleSheet.create({root:{flex:1,backgroundColor:t.bg},wrap:{padding:18,paddingBottom:42,gap:13},h1:{fontSize:27,fontWeight:'900',textAlign:'right',color:t.text},h2:{fontSize:19,fontWeight:'900',textAlign:'right',color:t.text,marginTop:5},p:{textAlign:'right',color:t.muted,lineHeight:23},label:{textAlign:'right',fontWeight:'800'},row:{flexDirection:'row-reverse',gap:8,flexWrap:'wrap'},two:{gap:10},btn:{backgroundColor:t.accent,borderRadius:16,padding:16,alignItems:'center'},btnT:{color:'#fff',fontWeight:'900'},outline:{borderWidth:1,borderColor:t.accent,borderRadius:15,padding:13,alignItems:'center'},outlineT:{color:t.accent,fontWeight:'900'},success:{backgroundColor:'#E8F7EF',borderRadius:16,padding:14},successT:{color:t.success,textAlign:'right',fontWeight:'800'}})
