import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { useMemo, useState } from 'react';
import { Alert, StyleSheet, TextInput, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { api } from '../src/api';
import { effectiveAudience, paletteFor } from '../src/prefs';
import { usePrefs } from '../src/usePrefs';
import { InternalHeader, NText } from '../src/ui';

export default function BusinessPostCreate(){const p=useLocalSearchParams<{businessId:string;businessName?:string}>();const[prefs]=usePrefs();const a=effectiveAudience(prefs);const t=paletteFor(a,prefs.appearance);const s=useMemo(()=>styles(t),[a,prefs.appearance]);const[title,setTitle]=useState('');const[body,setBody]=useState('');const[busy,setBusy]=useState(false);
const submit=async()=>{if(!title.trim()||!body.trim())return Alert.alert('متن کامل نیست','عنوان و متن پست را وارد کن.');setBusy(true);try{await api(`/v1/businesses/${p.businessId}/posts`,{method:'POST',body:JSON.stringify({title:title.trim(),body:body.trim(),visibility:'FOLLOWERS'})});Alert.alert('منتشر شد','این پست فقط برای کاربرانی که مجموعه را دنبال کرده‌اند در بلاگ نمایش داده می‌شود.',[{text:'باشه',onPress:()=>router.back()}])}catch(e:any){Alert.alert('انتشار انجام نشد',e.message||'سرویس انتشار در دسترس نیست.')}finally{setBusy(false)}};
return <SafeAreaView edges={['bottom']} style={s.root}><View style={s.wrap}><InternalHeader t={t} title="انتشار در بلاگ" sub={p.businessName||'کسب‌وکار نوبین'}/><View style={s.note}><Ionicons name="people-outline" size={18} color={t.accent}/><NText style={s.noteT}>این محتوا فقط در فید دنبال‌کنندگان همین مجموعه نمایش داده می‌شود؛ پیام‌های سراسری و منطقه‌ای فقط در اختیار مدیر سیستم است.</NText></View><TextInput value={title} onChangeText={setTitle} placeholder="عنوان اطلاعیه یا پست" placeholderTextColor={t.muted} style={s.title}/><TextInput multiline value={body} onChangeText={setBody} placeholder="متن پست، خبر، تغییر ساعت کاری، معرفی خدمت جدید و..." placeholderTextColor={t.muted} textAlignVertical="top" style={s.body}/><TouchableOpacity disabled={busy} activeOpacity={.75} onPress={submit} style={[s.btn,busy&&{opacity:.55}]}><Ionicons name="send-outline" size={18} color="#fff"/><NText weight="bold" style={s.btnT}>{busy?'در حال انتشار...':'انتشار برای دنبال‌کنندگان'}</NText></TouchableOpacity></View></SafeAreaView>}
const styles=(t:any)=>StyleSheet.create({root:{flex:1,backgroundColor:t.bg},wrap:{padding:18,gap:13},note:{backgroundColor:t.accentSoft,borderRadius:15,padding:12,flexDirection:'row-reverse',alignItems:'flex-start',gap:7},noteT:{flex:1,fontSize:11.5,lineHeight:20,color:t.accent,textAlign:'right'},title:{height:50,borderRadius:15,borderWidth:1,borderColor:t.line,backgroundColor:t.card,paddingHorizontal:13,fontFamily:'Vazirmatn_500Medium',fontSize:13,color:t.text,textAlign:'right'},body:{minHeight:180,borderRadius:15,borderWidth:1,borderColor:t.line,backgroundColor:t.card,padding:13,fontFamily:'Vazirmatn_400Regular',fontSize:13,lineHeight:22,color:t.text,textAlign:'right'},btn:{height:49,borderRadius:15,backgroundColor:t.accent,flexDirection:'row-reverse',alignItems:'center',justifyContent:'center',gap:7},btnT:{fontSize:13,color:'#fff'}})
