import { Ionicons } from '@expo/vector-icons';
import { useLocalSearchParams } from 'expo-router';
import { useEffect, useMemo, useState } from 'react';
import { Alert, ScrollView, StyleSheet, TextInput, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { api } from '../src/api';
import { defaultPrefs, paletteFor, type LocalPrefs } from '../src/prefs';
import { getPrefs } from '../src/session';
import { NText } from '../src/ui';

type StaffRow={id:number;name:string;service_ids?:number[]};
export default function BusinessManage(){
 const p=useLocalSearchParams<{businessId:string}>();const bid=Number(p.businessId||0);const[prefs,setPrefs]=useState<LocalPrefs>(defaultPrefs);const[b,setB]=useState<any>(null);const[staffName,setStaffName]=useState('');const[service,setService]=useState('');const[price,setPrice]=useState('');const[duration,setDuration]=useState('60');const[selectedStaffIds,setSelectedStaffIds]=useState<number[]>([]);const[loading,setLoading]=useState(true);const t=paletteFor(prefs.audience,prefs.appearance);const s=useMemo(()=>styles(t),[prefs.audience,prefs.appearance]);
 const load=async()=>{setLoading(true);try{const pref=await getPrefs();if(pref)setPrefs(pref);const j=await api(`/v1/me/businesses/${bid}`);setB(j.business)}catch(e:any){Alert.alert('خطا',e.message)}finally{setLoading(false)}};useEffect(()=>{if(bid)load()},[bid]);
 const staffRows:StaffRow[]=b?.staff||[];
 const addStaff=async()=>{if(!staffName.trim())return;try{await api(`/v1/businesses/${bid}/staff`,{method:'POST',body:JSON.stringify({name:staffName.trim(),gender:b?.gender==='ALL'?'UNSPECIFIED':b?.gender})});setStaffName('');await load()}catch(e:any){Alert.alert('ثبت نشد',e.message)}};
 const toggleStaff=(id:number)=>setSelectedStaffIds(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);
 const addService=async()=>{if(!service.trim())return;if(!staffRows.length)return Alert.alert('ابتدا متخصص اضافه کن');if(!selectedStaffIds.length)return Alert.alert('متخصص خدمت را انتخاب کن');if(Number(duration)<5||Number(price)<0)return Alert.alert('قیمت یا مدت معتبر نیست');try{await api(`/v1/businesses/${bid}/services`,{method:'POST',body:JSON.stringify({title:service.trim(),price:Number(price||0),duration_minutes:Number(duration),gender:b?.gender||'ALL',staff_ids:selectedStaffIds})});setService('');setPrice('');setSelectedStaffIds([]);await load()}catch(e:any){Alert.alert('ثبت نشد',e.message)}};
 const setMapping=async(serviceId:number,ids:number[])=>{if(!ids.length)return Alert.alert('حداقل یک متخصص لازم است');try{await api(`/v1/businesses/${bid}/staff-services`,{method:'POST',body:JSON.stringify({service_id:serviceId,staff_ids:ids})});await load()}catch(e:any){Alert.alert('ذخیره نشد',e.message)}};
 const addHours=async()=>{try{for(let w=0;w<7;w++)await api(`/v1/businesses/${bid}/shifts`,{method:'POST',body:JSON.stringify({weekday:w,start_time:'09:00',end_time:'20:00'})});Alert.alert('ساعات کاری ثبت شد');await load()}catch(e:any){Alert.alert('خطا',e.message)}};
 if(loading||!b)return <SafeAreaView edges={['bottom']} style={s.root}><NText style={s.loading}>در حال دریافت کسب‌وکار...</NText></SafeAreaView>;
 return <SafeAreaView edges={['bottom']} style={s.root}><ScrollView contentContainerStyle={s.wrap} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}><View style={s.head}><View style={{flex:1}}><NText weight="bold" style={s.h1}>{b.name}</NText><NText style={s.muted}>{[b.province,b.city].filter(Boolean).join('، ')} · {b.status==='APPROVED'?'تأییدشده':'در انتظار بررسی'}</NText></View><View style={[s.dot,{backgroundColor:b.status==='APPROVED'?t.success:t.warning}]}/></View>
 <Section n="۱" title="متخصص‌ها" t={t}/>{staffRows.length?<View style={s.card}>{staffRows.map(x=><View key={x.id} style={s.itemRow}><Ionicons name="person-circle-outline" size={20} color={t.accent}/><View style={{flex:1}}><NText weight="medium" style={s.itemTitle}>{x.name}</NText><NText style={s.muted}>{(x.service_ids||[]).length?`${(x.service_ids||[]).length} خدمت متصل`:'هنوز خدمتی متصل نیست'}</NText></View></View>)}</View>:<NText style={s.warning}>هنوز متخصصی ثبت نشده؛ تا آن زمان نوبت‌گیری غیرفعال است.</NText>}<Field label="نام متخصص جدید" value={staffName} set={setStaffName} t={t}/><Action title="افزودن متخصص" icon="person-add-outline" onPress={addStaff} t={t}/>
 <Section n="۲" title="خدمات فعلی" t={t}/>{(b.services||[]).length?<View style={s.card}>{(b.services||[]).map((sv:any)=>{const current=staffRows.filter(st=>(st.service_ids||[]).map(Number).includes(Number(sv.id))).map(st=>Number(st.id));return <ServiceMap key={sv.id} sv={sv} staff={staffRows} initial={current} save={(ids:number[])=>setMapping(Number(sv.id),ids)} t={t}/>})}</View>:<NText style={s.warning}>خدمتی ثبت نشده است.</NText>}
 <Section n="۳" title="افزودن خدمت" t={t}/><Field label="عنوان خدمت" value={service} set={setService} t={t}/><View style={s.row2}><View style={{flex:1}}><Field label="قیمت (تومان)" value={price} set={setPrice} t={t} numeric/></View><View style={{flex:1}}><Field label="مدت (دقیقه)" value={duration} set={setDuration} t={t} numeric/></View></View>{staffRows.length?<><NText weight="medium" style={s.label}>متخصص‌های این خدمت</NText><View style={s.chips}>{staffRows.map(x=><Chip key={x.id} label={x.name} on={selectedStaffIds.includes(Number(x.id))} onPress={()=>toggleStaff(Number(x.id))} t={t}/>)}</View></>:<NText style={s.warning}>ابتدا متخصص اضافه کن.</NText>}<Action title="ثبت خدمت" icon="add-circle-outline" onPress={addService} t={t}/>
 <Section n="۴" title="ساعات کاری" t={t}/><NText style={s.muted}>{(b.shifts||[]).length?`${(b.shifts||[]).length} بازه کاری ثبت شده است.`:'هنوز ساعت کاری ثبت نشده است.'}</NText><Action title="ثبت ساعت اولیه ۹ تا ۲۰" icon="time-outline" onPress={addHours} t={t}/>
 </ScrollView></SafeAreaView>
}
function ServiceMap({sv,staff,initial,save,t}:any){const[ids,setIds]=useState<number[]>(initial);useEffect(()=>setIds(initial),[initial.join(',')]);const toggle=(id:number)=>setIds(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);return <View style={{paddingVertical:10,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:t.line,gap:7}}><View style={{flexDirection:'row-reverse',justifyContent:'space-between',gap:8}}><View style={{flex:1}}><NText weight="semi" style={{fontSize:13,color:t.text,textAlign:'right'}}>{sv.title}</NText><NText style={{fontSize:10.5,color:t.muted,textAlign:'right'}}>{Number(sv.bookable_staff_count||0)>0?'قابل نوبت‌گیری':'بدون متخصص؛ نوبت‌گیری غیرفعال'}</NText></View><NText weight="medium" style={{fontSize:11,color:t.accent}}>{new Intl.NumberFormat('fa-IR').format(Number(sv.price||0))} تومان</NText></View><View style={{flexDirection:'row-reverse',gap:6,flexWrap:'wrap'}}>{staff.map((st:any)=><Chip key={st.id} label={st.name} on={ids.includes(Number(st.id))} onPress={()=>toggle(Number(st.id))} t={t}/>)}</View><TouchableOpacity onPress={()=>save(ids)} style={{alignSelf:'flex-start',paddingHorizontal:10,paddingVertical:6,borderRadius:10,backgroundColor:t.accentSoft}}><NText weight="semi" style={{fontSize:10.5,color:t.accent}}>ذخیره متخصص‌ها</NText></TouchableOpacity></View>}
function Section({n,title,t}:any){return <View style={{flexDirection:'row-reverse',alignItems:'center',gap:7,marginTop:5}}><View style={{width:25,height:25,borderRadius:9,backgroundColor:t.accentSoft,alignItems:'center',justifyContent:'center'}}><NText weight="bold" style={{fontSize:11,color:t.accent}}>{n}</NText></View><NText weight="semi" style={{fontSize:15,color:t.text}}>{title}</NText></View>}
function Field({label,value,set,t,numeric=false}:any){return <View style={{gap:5}}><NText weight="medium" style={{fontSize:11.2,color:t.muted,textAlign:'right'}}>{label}</NText><TextInput value={value} onChangeText={set} keyboardType={numeric?'number-pad':'default'} textAlign="right" placeholderTextColor={t.muted} style={{height:46,borderWidth:1,borderColor:t.line,backgroundColor:t.card,borderRadius:13,paddingHorizontal:11,fontFamily:'Vazirmatn_400Regular',fontSize:12.5,color:t.text}}/></View>}
function Chip({label,on,onPress,t}:any){return <TouchableOpacity onPress={onPress} style={{borderWidth:1,borderColor:on?t.accent:t.line,backgroundColor:on?t.accentSoft:t.card,borderRadius:11,paddingHorizontal:9,paddingVertical:7}}><NText weight={on?'semi':'regular'} style={{fontSize:10.5,color:on?t.accent:t.text}}>{label}</NText></TouchableOpacity>}
function Action({title,icon,onPress,t}:any){return <TouchableOpacity onPress={onPress} activeOpacity={.72} style={{height:44,borderWidth:1,borderColor:t.line,backgroundColor:t.card,borderRadius:13,flexDirection:'row-reverse',alignItems:'center',justifyContent:'center',gap:6}}><Ionicons name={icon} size={17} color={t.accent}/><NText weight="semi" style={{fontSize:11.5,color:t.accent}}>{title}</NText></TouchableOpacity>}
const styles=(t:any)=>StyleSheet.create({root:{flex:1,backgroundColor:t.bg},wrap:{padding:16,paddingBottom:36,gap:11},loading:{padding:24,textAlign:'center',color:t.muted},head:{flexDirection:'row-reverse',alignItems:'center',gap:10},dot:{width:9,height:9,borderRadius:5},h1:{fontSize:21,lineHeight:31,color:t.text,textAlign:'right'},muted:{fontSize:11.2,lineHeight:18,color:t.muted,textAlign:'right'},warning:{fontSize:11.2,lineHeight:19,color:t.warning,textAlign:'right'},card:{backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:16,paddingHorizontal:12},itemRow:{flexDirection:'row-reverse',alignItems:'center',gap:8,paddingVertical:10,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:t.line},itemTitle:{fontSize:12.5,color:t.text,textAlign:'right'},row2:{flexDirection:'row-reverse',gap:8},label:{fontSize:11.2,color:t.text,textAlign:'right'},chips:{flexDirection:'row-reverse',gap:6,flexWrap:'wrap'}})
