import { Ionicons } from '@expo/vector-icons';
import { useEffect, useMemo, useState } from 'react';
import { Alert, ScrollView, StyleSheet, TextInput, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { api } from '../src/api';
import { defaultPrefs, paletteFor, type LocalPrefs } from '../src/prefs';
import { getPrefs } from '../src/session';
import { NText } from '../src/ui';

export default function BusinessRegister(){const[prefs,setPrefs]=useState<LocalPrefs>(defaultPrefs);useEffect(()=>{getPrefs().then(p=>p&&setPrefs(p))},[]);const t=paletteFor(prefs.audience,prefs.appearance);const s=useMemo(()=>styles(t),[prefs.audience,prefs.appearance]);const[businessId,setBusinessId]=useState<number|null>(null);const[name,setName]=useState('');const[city,setCity]=useState(prefs.preferredCity||'');const[address,setAddress]=useState('');const[type,setType]=useState('SALON');const[gender,setGender]=useState('ALL');const[staff,setStaff]=useState('');const[service,setService]=useState('');const[price,setPrice]=useState('');const[duration,setDuration]=useState('60');const[resource,setResource]=useState('');
useEffect(()=>{if(!city&&prefs.preferredCity)setCity(prefs.preferredCity)},[prefs.preferredCity]);
const create=async()=>{if(!name.trim()||!city.trim())return Alert.alert('اطلاعات ناقص','نام کسب‌وکار و شهر را وارد کن.');try{const j=await api('/v1/businesses/register',{method:'POST',body:JSON.stringify({name,city,address,type,gender})});setBusinessId(Number(j.business.id));Alert.alert('ثبت اولیه انجام شد','حالا پرسنل، خدمات و ساعت کاری را تکمیل کن.')}catch(e:any){Alert.alert('ثبت ناموفق',e.message)}};
const addStaff=async()=>{if(!businessId||!staff.trim())return;try{await api(`/v1/businesses/${businessId}/staff`,{method:'POST',body:JSON.stringify({name:staff,gender:gender==='ALL'?'UNSPECIFIED':gender})});setStaff('');Alert.alert('انجام شد','پرسنل اضافه شد.')}catch(e:any){Alert.alert('خطا',e.message)}};
const addService=async()=>{if(!businessId||!service.trim())return;try{await api(`/v1/businesses/${businessId}/services`,{method:'POST',body:JSON.stringify({title:service,price:Number(price||0),duration_minutes:Number(duration||30),gender})});setService('');setPrice('');Alert.alert('انجام شد','خدمت اضافه شد.')}catch(e:any){Alert.alert('خطا',e.message)}};
const addResource=async()=>{if(!businessId||!resource.trim())return;try{await api(`/v1/businesses/${businessId}/resources`,{method:'POST',body:JSON.stringify({name:resource,type:'OTHER',capacity:1})});setResource('');Alert.alert('انجام شد','منبع/تجهیزات اضافه شد.')}catch(e:any){Alert.alert('خطا',e.message)}};
const addHours=async()=>{if(!businessId)return;try{for(let w=0;w<7;w++)await api(`/v1/businesses/${businessId}/shifts`,{method:'POST',body:JSON.stringify({weekday:w,start_time:'09:00',end_time:'20:00'})});Alert.alert('انجام شد','ساعت کاری اولیه ثبت شد و بعداً قابل ویرایش است.')}catch(e:any){Alert.alert('خطا',e.message)}};
return <SafeAreaView edges={['bottom']} style={s.root}><ScrollView contentContainerStyle={s.wrap} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}><View><NText weight="bold" style={s.h1}>{businessId?'تکمیل کسب‌وکار':'ثبت کسب‌وکار'}</NText><NText style={s.p}>{businessId?'پرسنل، خدمات، منابع و ساعت کاری را اضافه کن.':'سالن، آرایشگاه، کلینیک یا ارائه‌دهنده مستقل را ثبت کن.'}</NText></View>{!businessId?<><Section n="۱" title="اطلاعات پایه" t={t}/><Field label="نام کسب‌وکار" value={name} set={setName} t={t}/><Field label="شهر" value={city} set={setCity} t={t}/><Field label="آدرس" value={address} set={setAddress} t={t}/><Section n="۲" title="نوع فعالیت" t={t}/><View style={s.row}>{[['SALON','سالن / آرایشگاه'],['CLINIC','کلینیک'],['FREELANCER','مستقل']].map(([v,l])=><Chip key={v} on={type===v} label={l} press={()=>setType(v)} t={t}/>)}</View><Section n="۳" title="مخاطب خدمات" t={t}/><View style={s.row}>{[['FEMALE','بانوان'],['MALE','آقایان'],['ALL','هر دو']].map(([v,l])=><Chip key={v} on={gender===v} label={l} press={()=>setGender(v)} t={t}/>)}</View><TouchableOpacity activeOpacity={.75} style={s.btn} onPress={create}><NText weight="bold" style={s.btnT}>ثبت اولیه و ادامه</NText></TouchableOpacity></>:<><View style={s.success}><Ionicons name="checkmark-circle" size={21} color={t.success}/><NText weight="medium" style={s.successT}>کسب‌وکار #{businessId} ثبت شده و در انتظار بررسی است.</NText></View><Section n="۱" title="پرسنل / آرایشگر" t={t}/><Field label="نام پرسنل" value={staff} set={setStaff} t={t}/><Action title="افزودن پرسنل" icon="person-add-outline" onPress={addStaff} t={t}/><Section n="۲" title="خدمات" t={t}/><Field label="عنوان خدمت" value={service} set={setService} t={t}/><Field label="قیمت (تومان)" value={price} set={setPrice} numeric t={t}/><Field label="مدت (دقیقه)" value={duration} set={setDuration} numeric t={t}/><Action title="افزودن خدمت" icon="add-circle-outline" onPress={addService} t={t}/><Section n="۳" title="صندلی / اتاق / دستگاه" t={t}/><Field label="نام منبع" value={resource} set={setResource} t={t}/><Action title="افزودن منبع" icon="cube-outline" onPress={addResource} t={t}/><Section n="۴" title="ساعات کاری اولیه" t={t}/><NText style={s.p}>برای شروع ۰۹:۰۰ تا ۲۰:۰۰ ثبت می‌شود؛ ویرایش دقیق روزها در پنل مدیریت تکمیل خواهد شد.</NText><Action title="ثبت ساعت کاری اولیه" icon="time-outline" onPress={addHours} t={t}/></>}</ScrollView></SafeAreaView>}
function Section({n,title,t}:any){return <View style={{flexDirection:'row-reverse',alignItems:'center',gap:7,marginTop:4}}><View style={{width:25,height:25,borderRadius:9,backgroundColor:t.accentSoft,alignItems:'center',justifyContent:'center'}}><NText weight="bold" style={{fontSize:11,color:t.accent}}>{n}</NText></View><NText weight="semi" style={{fontSize:15,color:t.text}}>{title}</NText></View>}
function Field({label,value,set,numeric=false,t}:any){return <View style={{gap:5}}><NText weight="medium" style={{textAlign:'right',fontSize:11.5,color:t.muted}}>{label}</NText><TextInput value={value} onChangeText={set} keyboardType={numeric?'number-pad':'default'} textAlign="right" placeholderTextColor={t.muted} style={{height:47,backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:14,paddingHorizontal:12,fontFamily:'Vazirmatn_400Regular',fontSize:13,color:t.text}}/></View>}
function Chip({on,label,press,t}:any){return <TouchableOpacity activeOpacity={.72} onPress={press} style={{borderWidth:1,borderColor:on?t.accent:t.line,backgroundColor:on?t.accentSoft:t.card,borderRadius:13,paddingHorizontal:11,paddingVertical:9}}><NText weight={on?'semi':'medium'} style={{fontSize:11.5,color:on?t.accent:t.text}}>{label}</NText></TouchableOpacity>}
function Action({title,icon,onPress,t}:any){return <TouchableOpacity activeOpacity={.72} onPress={onPress} style={{height:44,borderWidth:1,borderColor:t.line,backgroundColor:t.card,borderRadius:13,flexDirection:'row-reverse',alignItems:'center',justifyContent:'center',gap:6}}><Ionicons name={icon} size={17} color={t.accent}/><NText weight="semi" style={{fontSize:11.5,color:t.accent}}>{title}</NText></TouchableOpacity>}
const styles=(t:any)=>StyleSheet.create({root:{flex:1,backgroundColor:t.bg},wrap:{padding:16,paddingBottom:36,gap:11},h1:{fontSize:22,lineHeight:33,textAlign:'right',color:t.text},p:{fontSize:11.8,lineHeight:20,textAlign:'right',color:t.muted},row:{flexDirection:'row-reverse',gap:7,flexWrap:'wrap'},btn:{height:48,backgroundColor:t.accent,borderRadius:14,alignItems:'center',justifyContent:'center',marginTop:4},btnT:{fontSize:12.5,color:'#fff'},success:{backgroundColor:'#EAF6F0',borderRadius:15,padding:12,flexDirection:'row-reverse',alignItems:'center',gap:7},successT:{fontSize:11.5,color:t.success,flex:1,textAlign:'right'}})
