import { router } from 'expo-router';
import { Text, TextInput, TouchableOpacity, View, StyleSheet, ScrollView } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useEffect, useMemo, useState } from 'react';
import { api } from '../src/api';
import { salonCard } from '../src/live';
import { getPrefs } from '../src/session';
import { audienceLabel, categoriesFor, paletteFor, type Audience } from '../src/prefs';
import type { Salon } from '../src/demo';
const fa=(n:number)=>new Intl.NumberFormat('fa-IR').format(n);
export default function Home(){const[q,setQ]=useState('');const[audience,setAudience]=useState<Audience>('ALL');const[rows,setRows]=useState<Salon[]>([]);const t=paletteFor(audience);const s=useMemo(()=>styles(t),[audience]);
useEffect(()=>{getPrefs().then(p=>{if(!p){router.replace('/onboarding');return}setAudience(p.audience)})},[]);
useEffect(()=>{let on=true;const g=audience==='ALL'?'':`&gender=${audience}`;api(`/v1/businesses?limit=3${g}`).then(j=>{if(on)setRows(Array.isArray(j?.items)?j.items.map(salonCard):[])}).catch(()=>{});return()=>{on=false}},[audience]);
const cats=categoriesFor(audience);
return <SafeAreaView edges={['top','bottom']} style={s.root}><ScrollView contentContainerStyle={s.wrap} showsVerticalScrollIndicator={false}>
<View style={s.top}><TouchableOpacity onPress={()=>router.push('/profile')} style={s.avatar}><Text style={s.avatarT}>ن</Text></TouchableOpacity><View><Text style={s.brand}>نوبین</Text><Text style={s.sub}>زیبایی و آراستگی، ساده و مطمئن</Text></View></View>
<View style={s.hero}><Text style={s.kicker}>{audienceLabel(audience)} · رزرو هوشمند</Text><Text style={s.h1}>وقت خوب، متخصص خوب، انتخاب مطمئن.</Text><Text style={s.p}>سالن، آرایشگر و زمان آزاد واقعی را متناسب با انتخاب خودت ببین.</Text></View>
<View style={s.search}><TextInput style={s.input} placeholder={audience==='MALE'?'مثلاً اصلاح ریش در تهران':audience==='FEMALE'?'مثلاً ناخن در تهران':'مثلاً خدمت یا محله'} placeholderTextColor={t.muted} value={q} onChangeText={setQ}/><TouchableOpacity style={s.btn} onPress={()=>router.push({pathname:'/search',params:{q,audience}})}><Text style={s.bt}>جستجو</Text></TouchableOpacity></View>
<TouchableOpacity style={s.ai} onPress={()=>router.push('/assistant')}><View style={s.aiIcon}><Text style={{fontSize:22}}>✦</Text></View><View style={{flex:1}}><Text style={s.aiTitle}>دستیار نوبین</Text><Text style={s.p}>نیازت را بنویس؛ زمان و گزینه مناسب را پیشنهاد می‌دهد.</Text></View><Text style={s.arrow}>‹</Text></TouchableOpacity>
<View style={s.sectionRow}><TouchableOpacity onPress={()=>router.push('/onboarding')}><Text style={s.more}>تغییر</Text></TouchableOpacity><Text style={s.h2}>دسته‌بندی‌های {audienceLabel(audience)}</Text></View>
<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}>{cats.map(x=><TouchableOpacity key={x.t} style={s.chip} onPress={()=>router.push({pathname:'/search',params:{q:x.t,audience}})}><Text style={s.chipEmoji}>{x.e}</Text><Text style={s.chipText}>{x.t}</Text></TouchableOpacity>)}</ScrollView>
<View style={s.sectionRow}><Text style={s.live}>داده زنده</Text><Text style={s.h2}>پیشنهاد نوبین</Text></View>{rows.length?rows.map(x=><TouchableOpacity key={x.id} style={s.salon} onPress={()=>router.push(`/business/${x.id}`)}><View style={s.photo}><Text style={s.photoTxt}>{x.name.slice(0,1)}</Text></View><View style={{flex:1,gap:5}}><Text style={s.salonName}>{x.name}</Text><Text style={s.p}>{x.neighborhood?`${x.neighborhood}، `:''}{x.city}</Text><View style={s.meta}><Text style={s.rating}>★ {x.rating||'—'} ({fa(x.reviews)})</Text><Text style={s.next}>{x.next}</Text></View></View></TouchableOpacity>):<Text style={s.p}>هنوز کسب‌وکاری برای این پروفایل تأیید نشده است.</Text>}
</ScrollView><View style={s.nav}><TouchableOpacity onPress={()=>router.push('/profile')}><Text style={s.navTxt}>حساب</Text></TouchableOpacity><TouchableOpacity onPress={()=>router.push('/bookings')}><Text style={s.navTxt}>نوبت‌ها</Text></TouchableOpacity><TouchableOpacity onPress={()=>router.push({pathname:'/search',params:{audience}})}><Text style={s.navTxt}>جستجو</Text></TouchableOpacity><Text style={[s.navTxt,s.navActive]}>خانه</Text></View></SafeAreaView>}
const styles=(t:any)=>StyleSheet.create({root:{flex:1,backgroundColor:t.bg},wrap:{paddingHorizontal:18,paddingTop:8,paddingBottom:16,gap:16},top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},avatar:{width:44,height:44,borderRadius:22,backgroundColor:t.accentSoft,alignItems:'center',justifyContent:'center'},avatarT:{fontWeight:'900',color:t.accent},brand:{fontSize:23,fontWeight:'900',textAlign:'right',color:t.accent},sub:{fontSize:12,color:t.muted,textAlign:'right',fontFamily:'sans-serif'},hero:{paddingTop:10,gap:9},kicker:{color:t.accent,fontWeight:'700',fontSize:15,textAlign:'right',fontFamily:'sans-serif-medium'},h1:{fontSize:30,fontWeight:'900',lineHeight:44,color:t.text,textAlign:'right'},h2:{fontSize:20,fontWeight:'900',color:t.text,textAlign:'right'},p:{color:t.muted,fontSize:14,lineHeight:23,textAlign:'right'},search:{backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:22,padding:8},input:{textAlign:'right',padding:12,fontSize:16,color:t.text},btn:{backgroundColor:t.accent,padding:13,borderRadius:15,alignItems:'center'},bt:{color:'#fff',fontWeight:'900'},ai:{flexDirection:'row-reverse',alignItems:'center',gap:12,backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:22,padding:16},aiIcon:{width:46,height:46,borderRadius:16,backgroundColor:t.accentSoft,alignItems:'center',justifyContent:'center'},aiTitle:{textAlign:'right',fontSize:17,fontWeight:'900',color:t.ink},arrow:{fontSize:30,color:t.accent},sectionRow:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:4},more:{color:t.accent,fontWeight:'800'},live:{color:t.success,fontWeight:'800'},chips:{gap:10,paddingVertical:2},chip:{width:96,backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:20,paddingVertical:13,alignItems:'center',gap:5},chipEmoji:{fontSize:21},chipText:{fontSize:13,fontWeight:'700',color:t.ink},salon:{flexDirection:'row-reverse',gap:12,backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:22,padding:12},photo:{width:82,height:82,borderRadius:18,backgroundColor:t.accentSoft,alignItems:'center',justifyContent:'center'},photoTxt:{fontSize:32,fontWeight:'900',color:t.accent},salonName:{fontSize:17,fontWeight:'900',textAlign:'right',color:t.text},meta:{flexDirection:'row-reverse',justifyContent:'space-between',alignItems:'center'},rating:{fontSize:12,color:t.warning,fontWeight:'700'},next:{fontSize:11,color:t.success,fontWeight:'700'},nav:{backgroundColor:t.card,borderTopWidth:1,borderTopColor:t.line,paddingVertical:14,paddingHorizontal:18,flexDirection:'row',justifyContent:'space-around'},navTxt:{fontSize:13,color:t.muted,fontWeight:'700'},navActive:{color:t.accent}})
