import { router } from 'expo-router';
import { SafeAreaView, Text, TextInput, TouchableOpacity, View, StyleSheet, ScrollView } from 'react-native';
import { useEffect, useState } from 'react';
import { c, shadow } from '../src/theme';
import { categories, salons, type Salon } from '../src/demo';
import { api } from '../src/api';
import { salonCard } from '../src/live';
const fa=(n:number)=>new Intl.NumberFormat('fa-IR').format(n);
export default function Home(){const[q,setQ]=useState('');const[rows,setRows]=useState<Salon[]>(salons.slice(0,2));useEffect(()=>{let on=true;api('/v1/businesses?limit=3').then(j=>{if(on&&Array.isArray(j?.items)&&j.items.length)setRows(j.items.map(salonCard))}).catch(()=>{});return()=>{on=false}},[]);return <SafeAreaView style={s.root}><ScrollView contentContainerStyle={s.wrap} showsVerticalScrollIndicator={false}>
<View style={s.top}><TouchableOpacity onPress={()=>router.push('/profile')} style={s.avatar}><Text>ن</Text></TouchableOpacity><View><Text style={s.brand}>نوبین</Text><Text style={s.sub}>زیبایی، بدون دردسر</Text></View></View>
<View style={s.hero}><Text style={s.kicker}>رزرو هوشمند خدمات زیبایی</Text><Text style={s.h1}>وقت خوب، متخصص خوب، انتخاب مطمئن.</Text><Text style={s.p}>از بین سالن‌ها و متخصص‌های تأییدشده انتخاب کن و زمان آزاد واقعی را ببین.</Text></View>
<View style={s.search}><TextInput style={s.input} placeholder="مثلاً ناخن در تهران" placeholderTextColor="#A4939D" value={q} onChangeText={setQ}/><TouchableOpacity style={s.btn} onPress={()=>router.push({pathname:'/search',params:{q}})}><Text style={s.bt}>جستجو</Text></TouchableOpacity></View>
<TouchableOpacity style={s.ai} onPress={()=>router.push('/assistant')}><View style={s.aiIcon}><Text style={{fontSize:22}}>✦</Text></View><View style={{flex:1}}><Text style={s.aiTitle}>دستیار زیبایی نوبین</Text><Text style={s.p}>نیازت را ساده بنویس؛ زمان و گزینه مناسب را پیشنهاد می‌دهد.</Text></View><Text style={s.arrow}>‹</Text></TouchableOpacity>
<View style={s.sectionRow}><TouchableOpacity onPress={()=>router.push('/search')}><Text style={s.more}>همه</Text></TouchableOpacity><Text style={s.h2}>دسته‌بندی‌ها</Text></View>
<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}>{categories.map((x,i)=><TouchableOpacity key={x} style={s.chip} onPress={()=>router.push({pathname:'/search',params:{q:x}})}><Text style={s.chipEmoji}>{['✂️','💅','✨','💄','👁️','🧔','🏠'][i]}</Text><Text style={s.chipText}>{x}</Text></TouchableOpacity>)}</ScrollView>
<View style={s.sectionRow}><Text style={s.more}>داده زنده نوبین</Text><Text style={s.h2}>پیشنهاد نوبین</Text></View>
{rows.slice(0,3).map(x=><TouchableOpacity key={x.id} style={s.salon} onPress={()=>router.push(`/business/${x.id}`)}><View style={s.photo}><Text style={s.photoTxt}>{x.name.slice(0,1)}</Text></View><View style={{flex:1,gap:5}}><Text style={s.salonName}>{x.name}</Text><Text style={s.p}>{x.neighborhood?`${x.neighborhood}، `:''}{x.city}</Text><View style={s.meta}><Text style={s.rating}>★ {x.rating||'—'} ({fa(x.reviews)})</Text><Text style={s.next}>{x.next}</Text></View></View></TouchableOpacity>)}
<View style={s.nav}><TouchableOpacity onPress={()=>router.push('/profile')}><Text style={s.navTxt}>حساب</Text></TouchableOpacity><TouchableOpacity onPress={()=>router.push('/bookings')}><Text style={s.navTxt}>نوبت‌ها</Text></TouchableOpacity><TouchableOpacity onPress={()=>router.push('/search')}><Text style={s.navTxt}>جستجو</Text></TouchableOpacity><Text style={[s.navTxt,s.navActive]}>خانه</Text></View>
</ScrollView></SafeAreaView>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:c.bg},wrap:{padding:18,paddingBottom:34,gap:16},top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},avatar:{width:42,height:42,borderRadius:21,backgroundColor:c.accentSoft,alignItems:'center',justifyContent:'center'},brand:{fontSize:22,fontWeight:'900',textAlign:'right',color:c.accent},sub:{fontSize:12,color:c.muted,textAlign:'right'},hero:{paddingTop:8,gap:8},kicker:{color:c.accent,fontWeight:'800',textAlign:'right'},h1:{fontSize:29,fontWeight:'900',lineHeight:42,color:c.text,textAlign:'right'},h2:{fontSize:20,fontWeight:'900',color:c.text,textAlign:'right'},p:{color:c.muted,fontSize:14,lineHeight:22,textAlign:'right'},search:{backgroundColor:c.card,borderWidth:1,borderColor:c.line,borderRadius:22,padding:8,...shadow},input:{textAlign:'right',padding:12,fontSize:16,color:c.text},btn:{backgroundColor:c.accent,padding:13,borderRadius:15,alignItems:'center'},bt:{color:'#fff',fontWeight:'900'},ai:{flexDirection:'row-reverse',alignItems:'center',gap:12,backgroundColor:'#fff',borderWidth:1,borderColor:c.line,borderRadius:22,padding:16},aiIcon:{width:46,height:46,borderRadius:16,backgroundColor:c.accentSoft,alignItems:'center',justifyContent:'center'},aiTitle:{textAlign:'right',fontSize:17,fontWeight:'900',color:c.ink},arrow:{fontSize:30,color:c.accent},sectionRow:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:4},more:{color:c.accent,fontWeight:'700'},chips:{gap:10,paddingVertical:2},chip:{width:92,backgroundColor:'#fff',borderWidth:1,borderColor:c.line,borderRadius:20,paddingVertical:13,alignItems:'center',gap:5},chipEmoji:{fontSize:21},chipText:{fontSize:13,fontWeight:'700',color:c.ink},salon:{flexDirection:'row-reverse',gap:12,backgroundColor:'#fff',borderWidth:1,borderColor:c.line,borderRadius:22,padding:12,...shadow},photo:{width:82,height:82,borderRadius:18,backgroundColor:c.accentSoft,alignItems:'center',justifyContent:'center'},photoTxt:{fontSize:32,fontWeight:'900',color:c.accent},salonName:{fontSize:17,fontWeight:'900',textAlign:'right',color:c.text},meta:{flexDirection:'row-reverse',justifyContent:'space-between',alignItems:'center'},rating:{fontSize:12,color:c.warning,fontWeight:'700'},next:{fontSize:11,color:c.success,fontWeight:'700'},nav:{marginTop:6,backgroundColor:'#fff',borderRadius:20,borderWidth:1,borderColor:c.line,padding:14,flexDirection:'row',justifyContent:'space-around'},navTxt:{fontSize:13,color:c.muted,fontWeight:'700'},navActive:{color:c.accent}})
