import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useState } from 'react';
import { Alert, Linking, StyleSheet, TextInput, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { api } from '../src/api';
import { defaultPrefs, paletteFor } from '../src/prefs';
import { savePrefs, setSession } from '../src/session';
import { NText } from '../src/ui';

export default function Login(){const[code,setCode]=useState('');const[busy,setBusy]=useState(false);const t=paletteFor('ALL');const s=styles(t);
const verify=async()=>{const c=code.replace(/\D/g,'');if(c.length!==6)return Alert.alert('کد نامعتبر','کد ورود باید ۶ رقمی باشد.');setBusy(true);try{const j=await api('/v1/auth/bale/verify',{method:'POST',body:JSON.stringify({code:c})});await setSession(j.token,j.user);const a=j.user?.service_audience||'ALL';await savePrefs({...defaultPrefs,audience:a});router.replace(j.user?.service_audience?'/profile':'/onboarding')}catch(e:any){Alert.alert('ورود ناموفق',e.message)}finally{setBusy(false)}};
return <SafeAreaView edges={['bottom']} style={s.root}><View style={s.wrap}><View style={s.icon}><Ionicons name="chatbubble-ellipses-outline" size={24} color={t.accent}/></View><NText weight="extra" style={s.brand}>نوبین</NText><NText weight="bold" style={s.h1}>ورود با بله</NText><NText style={s.p}>در ربات نوبین «ورود به اپ» را بزن و کد ۶ رقمی را اینجا وارد کن.</NText><TouchableOpacity activeOpacity={.72} style={s.outline} onPress={()=>Linking.openURL('https://ble.ir/nobin_bot?start=login')}><Ionicons name="open-outline" size={18} color={t.accent}/><NText weight="semi" style={s.outlineT}>باز کردن ربات نوبین</NText></TouchableOpacity><TextInput value={code} onChangeText={setCode} keyboardType="number-pad" maxLength={6} placeholder="کد ۶ رقمی" placeholderTextColor={t.muted} textAlign="center" style={s.input}/><TouchableOpacity disabled={busy} activeOpacity={.75} style={[s.btn,busy&&{opacity:.55}]} onPress={verify}><NText weight="bold" style={s.btnT}>{busy?'در حال بررسی...':'ورود'}</NText></TouchableOpacity><NText style={s.note}>شماره موبایل بعد از ورود، با اشتراک Contact رسمی در بله قابل تأیید است.</NText></View></SafeAreaView>}
const styles=(t:any)=>StyleSheet.create({root:{flex:1,backgroundColor:t.bg},wrap:{padding:22,gap:12},icon:{width:46,height:46,borderRadius:15,backgroundColor:t.accentSoft,alignItems:'center',justifyContent:'center'},brand:{fontSize:24,color:t.accent,textAlign:'right'},h1:{fontSize:24,lineHeight:36,textAlign:'right',color:t.text,marginTop:4},p:{fontSize:13.5,color:t.muted,textAlign:'right',lineHeight:23},outline:{height:48,borderWidth:1,borderColor:t.line,backgroundColor:t.card,borderRadius:15,paddingHorizontal:13,flexDirection:'row-reverse',alignItems:'center',justifyContent:'center',gap:7},outlineT:{fontSize:12.5,color:t.accent},input:{backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:15,padding:14,fontFamily:'Vazirmatn_600SemiBold',fontSize:21,letterSpacing:5,color:t.text},btn:{backgroundColor:t.accent,borderRadius:15,padding:14,alignItems:'center'},btnT:{color:'#fff',fontSize:13.5},note:{textAlign:'right',color:t.muted,fontSize:11.5,lineHeight:19}})
