import { router } from 'expo-router';
import { useState } from 'react';
import { Alert, Linking, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { api } from '../src/api';
import { setSession, savePrefs } from '../src/session';
import { paletteFor } from '../src/prefs';

export default function Login(){const[code,setCode]=useState('');const[busy,setBusy]=useState(false);const t=paletteFor('ALL');const s=styles(t);
const verify=async()=>{const c=code.replace(/\D/g,'');if(c.length!==6)return Alert.alert('کد نامعتبر','کد ورود باید ۶ رقمی باشد.');setBusy(true);try{const j=await api('/v1/auth/bale/verify',{method:'POST',body:JSON.stringify({code:c})});await setSession(j.token,j.user);const g=j.user?.profile_gender||'UNSPECIFIED';const a=j.user?.service_audience||'ALL';if(g!=='UNSPECIFIED')await savePrefs({profileGender:g,audience:a});router.replace(g==='UNSPECIFIED'?'/onboarding':'/profile')}catch(e:any){Alert.alert('ورود ناموفق',e.message)}finally{setBusy(false)}};
return <SafeAreaView edges={['bottom']} style={s.root}><View style={s.wrap}><Text style={s.brand}>نوبین</Text><Text style={s.h1}>ورود با بله</Text><Text style={s.p}>در ربات نوبین روی «🔐 ورود به اپ» بزن و کد ۶ رقمی را اینجا وارد کن.</Text><TouchableOpacity style={s.outline} onPress={()=>Linking.openURL('https://ble.ir/nobin_bot?start=login')}><Text style={s.outlineT}>باز کردن ربات نوبین در بله</Text></TouchableOpacity><TextInput value={code} onChangeText={setCode} keyboardType="number-pad" maxLength={6} placeholder="کد ۶ رقمی" textAlign="center" style={s.input}/><TouchableOpacity disabled={busy} style={s.btn} onPress={verify}><Text style={s.btnT}>{busy?'در حال بررسی...':'ورود'}</Text></TouchableOpacity><Text style={s.note}>پس از ورود، شماره موبایل را هم می‌توانی با دکمه رسمی اشتراک Contact در بله تأیید کنی.</Text></View></SafeAreaView>}
const styles=(t:any)=>StyleSheet.create({root:{flex:1,backgroundColor:t.bg},wrap:{padding:22,gap:16},brand:{fontSize:27,fontWeight:'900',color:t.accent,textAlign:'right'},h1:{fontSize:28,fontWeight:'900',textAlign:'right',color:t.text},p:{color:t.muted,textAlign:'right',lineHeight:25},outline:{borderWidth:1,borderColor:t.accent,borderRadius:16,padding:14},outlineT:{textAlign:'center',color:t.accent,fontWeight:'900'},input:{backgroundColor:'#fff',borderWidth:1,borderColor:t.line,borderRadius:16,padding:15,fontSize:22,letterSpacing:6,color:t.text},btn:{backgroundColor:t.accent,borderRadius:16,padding:16,alignItems:'center'},btnT:{color:'#fff',fontWeight:'900',fontSize:16},note:{textAlign:'right',color:t.muted,fontSize:12,lineHeight:20}})
