import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useState } from 'react';
import { Alert, Linking, StyleSheet, TextInput, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { api } from '../src/api';
import { defaultPrefs, paletteFor } from '../src/prefs';
import { savePrefs, setSession } from '../src/session';
import { NText } from '../src/ui';

export default function Login(){const[code,setCode]=useState('');const[busy,setBusy]=useState(false);const t=paletteFor('ALL');const s=styles(t);
const verify=async()=>{const c=code.replace(/\D/g,'');if(c.length!==6)return Alert.alert('کد نامعتبر','کد ورود باید ۶ رقمی باشد.');setBusy(true);try{const j=await api('/v1/auth/bale/verify',{method:'POST',body:JSON.stringify({code:c})});await setSession(j.token,j.user);const g=j.user?.profile_gender;const a=(g==='FEMALE'||g==='MALE')?g:(j.user?.service_audience||'ALL');await savePrefs({...defaultPrefs,profileGender:(g==='FEMALE'||g==='MALE')?g:'UNSPECIFIED',audience:a});router.replace('/') }catch(e:any){Alert.alert('ورود ناموفق',e.message)}finally{setBusy(false)}};
return <SafeAreaView edges={['bottom']} style={s.root}><View style={s.wrap}><View style={s.icon}><Ionicons name="chatbubble-ellipses-outline" size={24} color={t.accent}/></View><NText weight="extra" style={s.brand}>نوبین</NText><NText weight="bold" style={s.h1}>ورود با بله</NText><View style={s.guide}><Step n="۱" text="ربات نوبین را در بله باز کن." t={t}/><Step n="۲" text="اگر لازم بود شروع را بزن، سپس حتماً دکمه «ورود به اپلیکیشن» را انتخاب کن." t={t}/><Step n="۳" text="کد ۶ رقمی نمایش‌داده‌شده در ربات را در کادر پایین وارد کن." t={t}/></View><TouchableOpacity activeOpacity={.72} style={s.outline} onPress={()=>Linking.openURL('https://ble.ir/nobin_bot?start=login')}><Ionicons name="open-outline" size={18} color={t.accent}/><NText weight="semi" style={s.outlineT}>باز کردن ربات نوبین در بله</NText></TouchableOpacity><TextInput value={code} onChangeText={setCode} keyboardType="number-pad" maxLength={6} placeholder="کد ۶ رقمی" placeholderTextColor={t.muted} textAlign="center" style={s.input}/><TouchableOpacity disabled={busy} activeOpacity={.75} style={[s.btn,busy&&{opacity:.55}]} onPress={verify}><NText weight="bold" style={s.btnT}>{busy?'در حال بررسی...':'ورود'}</NText></TouchableOpacity><NText style={s.note}>فقط ورود به ربات کافی نیست؛ صدور کد پس از زدن دکمه «ورود به اپلیکیشن» انجام می‌شود.</NText></View></SafeAreaView>}
function Step({n,text,t}:any){return <View style={{flexDirection:'row-reverse',alignItems:'flex-start',gap:8}}><View style={{width:24,height:24,borderRadius:8,backgroundColor:t.accentSoft,alignItems:'center',justifyContent:'center'}}><NText weight="bold" style={{fontSize:10,color:t.accent}}>{n}</NText></View><NText style={{flex:1,fontSize:12.2,lineHeight:21,color:t.text,textAlign:'right'}}>{text}</NText></View>}
const styles=(t:any)=>StyleSheet.create({root:{flex:1,backgroundColor:t.bg},wrap:{padding:22,gap:12},icon:{width:46,height:46,borderRadius:15,backgroundColor:t.accentSoft,alignItems:'center',justifyContent:'center'},brand:{fontSize:24,color:t.accent,textAlign:'right'},h1:{fontSize:24,lineHeight:36,textAlign:'right',color:t.text,marginTop:4},guide:{backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:17,padding:13,gap:10},outline:{height:48,borderWidth:1,borderColor:t.line,backgroundColor:t.card,borderRadius:15,paddingHorizontal:13,flexDirection:'row-reverse',alignItems:'center',justifyContent:'center',gap:7},outlineT:{fontSize:12.5,color:t.accent},input:{backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:15,padding:14,fontFamily:'Vazirmatn_600SemiBold',fontSize:21,letterSpacing:5,color:t.text},btn:{backgroundColor:t.accent,borderRadius:15,padding:14,alignItems:'center'},btnT:{color:'#fff',fontSize:13.5},note:{textAlign:'right',color:t.muted,fontSize:11.5,lineHeight:19}})
