import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useEffect, useMemo, useState } from 'react';
import { Alert, ScrollView, StyleSheet, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { api } from '../src/api';
import { appearanceLabel, audienceLongLabel, defaultPrefs, effectiveAudience, paletteFor, type Appearance, type Audience, type Density, type LocalPrefs, type ProfileGender } from '../src/prefs';
import { getPrefs, getToken, savePrefs, subscribePrefs } from '../src/session';
import { NText } from '../src/ui';

export default function Preferences(){
  const[prefs,setPrefs]=useState<LocalPrefs>(defaultPrefs);const[saved,setSaved]=useState(false);const[logged,setLogged]=useState(false);
  useEffect(()=>{let alive=true;(async()=>{const p=await getPrefs();if(p&&alive)setPrefs(p);const token=await getToken();if(!alive)return;setLogged(Boolean(token));if(token)try{const j=await api('/v1/me');const g=(j.user?.profile_gender||p?.profileGender||'UNSPECIFIED') as ProfileGender;const next={...(p||defaultPrefs),profileGender:g,audience:g==='UNSPECIFIED'?(p?.audience||'ALL'):g};setPrefs(next);await savePrefs(next)}catch{}})();const off=subscribePrefs(p=>setPrefs(p));return()=>{alive=false;off()}},[]);
  const audience=effectiveAudience(prefs);const t=paletteFor(audience,prefs.appearance);const s=useMemo(()=>styles(t),[audience,prefs.appearance]);
  const patch=(x:Partial<LocalPrefs>)=>{setSaved(false);setPrefs(p=>({...p,...x}))};
  const chooseGender=(g:ProfileGender)=>patch({profileGender:g,audience:g as Audience});
  const chooseAppearance=async(a:Appearance)=>{const next={...prefs,appearance:a};setPrefs(next);setSaved(false);await savePrefs(next)};
  const save=async()=>{try{const next=await savePrefs({...prefs,audience:effectiveAudience(prefs)});setPrefs(next);if(await getToken())await api('/v1/me/preferences',{method:'PATCH',body:JSON.stringify({profile_gender:next.profileGender,service_audience:next.audience})});setSaved(true)}catch(e:any){Alert.alert('ذخیره نشد',e.message||'خطایی رخ داد.')}};
  return <SafeAreaView edges={['bottom']} style={s.root}><ScrollView contentContainerStyle={s.wrap} keyboardShouldPersistTaps="handled">
    <View><NText weight="bold" style={s.h1}>تجربه نوبین را تنظیم کن</NText><NText style={s.p}>جنسیت حساب، خدمات قابل نمایش را تعیین می‌کند؛ خدمات جنسیت مقابل در جستجو، پروفایل مجموعه و رزرو نمایش داده نمی‌شود.</NText></View>
    {logged?<Section title="جنسیت حساب" sub="برای نمایش خدمات و قواعد ثبت کسب‌وکار"><View style={s.segment}>{(['FEMALE','MALE'] as ProfileGender[]).map(g=><Choice key={g} label={g==='FEMALE'?'خانم':'آقا'} on={prefs.profileGender===g} onPress={()=>chooseGender(g)} t={t}/>)}</View>{prefs.profileGender==='UNSPECIFIED'?<NText style={s.hint}>برای شخصی‌سازی دقیق خدمات، جنسیت حساب را مشخص کن.</NText>:null}</Section>:<Section title="نوع خدمات" sub="برای کاربر مهمان"><View style={s.segment}>{(['FEMALE','MALE','ALL'] as Audience[]).map(a=><Choice key={a} label={audienceLongLabel(a)} on={prefs.audience===a} onPress={()=>patch({audience:a})} t={t}/>)}</View></Section>}
    <Section title="رنگ و حال‌وهوای اپ" sub="تغییر تم بلافاصله اعمال و ذخیره می‌شود"><View style={s.grid}>{(['AUTO','ROSE','TEAL','NEUTRAL'] as Appearance[]).map(a=><Choice key={a} label={appearanceLabel(a)} on={prefs.appearance===a} onPress={()=>chooseAppearance(a)} t={t}/>)}</View></Section>
    <Section title="استان و شهر" sub="فیلتر ثابت جستجو و صفحه اصلی"><TouchableOpacity activeOpacity={.72} onPress={()=>router.push('/location-filter')} style={s.location}><Ionicons name="location-outline" size={19} color={t.accent}/><View style={{flex:1}}><NText weight="medium" style={s.locationTitle}>{prefs.preferredCity||'سراسر ایران'}</NText><NText style={s.locationSub}>{prefs.preferredProvince||'بدون محدودیت استانی'}</NText></View><Ionicons name="chevron-back" size={17} color={t.muted}/></TouchableOpacity></Section>
    <Section title="چیدمان خانه" sub="کارت‌های خلوت‌تر یا فشرده‌تر"><View style={s.segment}>{(['COMFORTABLE','COMPACT'] as Density[]).map(d=><Choice key={d} label={d==='COMFORTABLE'?'راحت':'فشرده'} on={prefs.density===d} onPress={()=>patch({density:d})} t={t}/>)}</View></Section>
    <Section title="دستیار هوشمند" sub="نمایش کارت دستیار در صفحه خانه"><TouchableOpacity activeOpacity={.7} onPress={()=>patch({showAssistant:!prefs.showAssistant})} style={s.toggleRow}><View style={[s.switch,{backgroundColor:prefs.showAssistant?t.accent:t.line}]}><View style={[s.knob,{alignSelf:prefs.showAssistant?'flex-end':'flex-start'}]}/></View><NText weight="medium" style={{color:t.text}}>{prefs.showAssistant?'نمایش داده شود':'پنهان باشد'}</NText></TouchableOpacity></Section>
    <TouchableOpacity activeOpacity={.75} style={s.save} onPress={save}><NText weight="bold" style={s.saveT}>{saved?'ذخیره شد ✓':'ذخیره شخصی‌سازی'}</NText></TouchableOpacity>
  </ScrollView></SafeAreaView>
}
function Section({title,sub,children}:any){return <View style={{gap:10}}><View><NText weight="semi" style={{fontSize:16,textAlign:'right'}}>{title}</NText><NText style={{fontSize:12.5,textAlign:'right',opacity:.65,marginTop:2,lineHeight:20}}>{sub}</NText></View>{children}</View>}
function Choice({label,on,onPress,t}:any){return <TouchableOpacity activeOpacity={.72} onPress={onPress} style={[{borderWidth:1,borderColor:t.line,backgroundColor:t.card,borderRadius:15,paddingHorizontal:12,paddingVertical:10},on&&{borderColor:t.accent,backgroundColor:t.accentSoft}]}><NText weight={on?'semi':'medium'} style={{fontSize:12.5,color:on?t.accent:t.text,textAlign:'center'}}>{label}</NText></TouchableOpacity>}
const styles=(t:any)=>StyleSheet.create({root:{flex:1,backgroundColor:t.bg},wrap:{padding:18,paddingBottom:36,gap:26},h1:{fontSize:24,lineHeight:36,textAlign:'right',color:t.text},p:{fontSize:13.5,lineHeight:23,textAlign:'right',color:t.muted,marginTop:4},hint:{fontSize:11.5,lineHeight:19,textAlign:'right',color:t.warning},segment:{flexDirection:'row-reverse',gap:8,flexWrap:'wrap'},grid:{flexDirection:'row-reverse',gap:8,flexWrap:'wrap'},location:{minHeight:54,borderRadius:15,borderWidth:1,borderColor:t.line,backgroundColor:t.card,flexDirection:'row-reverse',alignItems:'center',paddingHorizontal:13,gap:9},locationTitle:{fontSize:13,color:t.text,textAlign:'right'},locationSub:{fontSize:10.5,color:t.muted,textAlign:'right',marginTop:2},toggleRow:{height:48,borderRadius:15,borderWidth:1,borderColor:t.line,backgroundColor:t.card,paddingHorizontal:13,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},switch:{width:44,height:24,borderRadius:12,padding:3,justifyContent:'center'},knob:{width:18,height:18,borderRadius:9,backgroundColor:'#fff'},save:{backgroundColor:t.accent,borderRadius:16,padding:15,alignItems:'center'},saveT:{color:'#fff',fontSize:14.5}})
