import { router } from 'expo-router';
import { useEffect, useMemo, useState } from 'react';
import { Alert, Linking, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { api } from '../src/api';
import { clearSession, getPrefs, getToken, savePrefs, saveStoredUser } from '../src/session';
import { audienceLabel, paletteFor, type Audience, type ProfileGender } from '../src/prefs';
export default function Profile(){const[user,setUser]=useState<any>(null);const[audience,setAudience]=useState<Audience>('ALL');const[logged,setLogged]=useState(false);const t=paletteFor(audience);const s=useMemo(()=>styles(t),[audience]);const load=async()=>{const p=await getPrefs();if(p)setAudience(p.audience);const tok=await getToken();setLogged(Boolean(tok));if(!tok)return;try{const j=await api('/v1/me');setUser(j.user);await saveStoredUser(j.user)}catch(e:any){if(e.status===401){await clearSession();setLogged(false)}}};useEffect(()=>{load()},[]);
const choose=async(a:Audience)=>{setAudience(a);const gender:(ProfileGender)=user?.profile_gender||'UNSPECIFIED';await savePrefs({profileGender:gender,audience:a});if(logged)try{const j=await api('/v1/me/preferences',{method:'PATCH',body:JSON.stringify({profile_gender:gender,service_audience:a})});setUser(j.user)}catch{}};
const logout=async()=>{try{await api('/v1/auth/logout',{method:'POST'})}catch{}await clearSession();setUser(null);setLogged(false);Alert.alert('خروج انجام شد')};
return <SafeAreaView edges={['bottom']} style={s.root}><ScrollView contentContainerStyle={s.wrap}>{logged?<><View style={s.user}><View style={s.avatar}><Text style={s.avatarT}>{(user?.name||'ن')[0]}</Text></View><View style={{flex:1}}><Text style={s.name}>{user?.name||'کاربر نوبین'}</Text><Text style={s.muted}>{user?.phone_verified_at?`شماره تأییدشده: ${user.phone}`:'شماره موبایل هنوز تأیید نشده'}</Text><Text style={s.muted}>اتصال بله: {user?.bale_status==='ACTIVE'?'فعال':'نیاز به اتصال مجدد'}</Text></View></View>{!user?.phone_verified_at&&<View style={s.warn}><Text style={s.warnT}>برای ثبت نهایی نوبت و ثبت کسب‌وکار، شماره موبایل باید تأیید شود.</Text><TouchableOpacity style={s.btn} onPress={()=>Linking.openURL('https://ble.ir/nobin_bot?start=phone')}><Text style={s.btnT}>تأیید شماره در بله</Text></TouchableOpacity><TouchableOpacity style={s.outline} onPress={load}><Text style={s.outlineT}>بررسی مجدد وضعیت</Text></TouchableOpacity></View>}<View style={s.card}><Text style={s.h}>پروفایل خدمات</Text><Text style={s.muted}>جنسیت حساب و نوع خدمات جدا هستند؛ این گزینه فقط پیشنهادها و ظاهر را تنظیم می‌کند.</Text><View style={s.row}>{(['FEMALE','MALE','ALL'] as Audience[]).map(a=><TouchableOpacity key={a} onPress={()=>choose(a)} style={[s.chip,audience===a&&s.chipOn]}><Text style={[s.chipT,audience===a&&s.chipTOn]}>{audienceLabel(a)}</Text></TouchableOpacity>)}</View></View><TouchableOpacity style={s.business} onPress={()=>router.push('/business-dashboard')}><Text style={s.businessArrow}>‹</Text><View><Text style={s.businessTitle}>مدیریت یا ثبت کسب‌وکار</Text><Text style={s.businessSub}>سالن، آرایشگر، پرسنل، خدمات و زمان‌بندی</Text></View></TouchableOpacity><TouchableOpacity style={s.outline} onPress={logout}><Text style={s.outlineT}>خروج از حساب نوبین</Text></TouchableOpacity></>:<View style={s.card}><Text style={s.h}>هنوز وارد نشده‌اید</Text><Text style={s.muted}>برای رزرو نهایی و مدیریت نوبت‌ها با کد بله وارد شوید.</Text><TouchableOpacity style={s.btn} onPress={()=>router.push('/login')}><Text style={s.btnT}>ورود با بله</Text></TouchableOpacity></View>}<Text style={s.version}>نوبین ۲.۰.۲ · هویت مستقل نوبین + اتصال بله</Text></ScrollView></SafeAreaView>}
const styles=(t:any)=>StyleSheet.create({root:{flex:1,backgroundColor:t.bg},wrap:{padding:18,paddingBottom:40,gap:15},user:{backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:22,padding:16,flexDirection:'row-reverse',gap:12,alignItems:'center'},avatar:{width:56,height:56,borderRadius:18,backgroundColor:t.accentSoft,alignItems:'center',justifyContent:'center'},avatarT:{fontSize:23,fontWeight:'900',color:t.accent},name:{fontSize:18,fontWeight:'900',textAlign:'right',color:t.text},muted:{color:t.muted,textAlign:'right',lineHeight:22},card:{backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:20,padding:16,gap:12},h:{fontSize:18,fontWeight:'900',textAlign:'right',color:t.text},row:{flexDirection:'row-reverse',gap:7,flexWrap:'wrap'},chip:{borderWidth:1,borderColor:t.line,borderRadius:14,paddingHorizontal:11,paddingVertical:9},chipOn:{backgroundColor:t.accent,borderColor:t.accent},chipT:{fontWeight:'700',color:t.ink},chipTOn:{color:'#fff'},warn:{backgroundColor:'#FFF5E9',borderRadius:20,padding:16,gap:10},warnT:{textAlign:'right',color:'#7A4E10',lineHeight:22,fontWeight:'700'},btn:{backgroundColor:t.accent,borderRadius:15,padding:14,alignItems:'center'},btnT:{color:'#fff',fontWeight:'900'},outline:{borderWidth:1,borderColor:t.line,borderRadius:15,padding:13,alignItems:'center'},outlineT:{color:t.accent,fontWeight:'900'},business:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',backgroundColor:t.ink,borderRadius:20,padding:16},businessTitle:{color:'#fff',fontWeight:'900',fontSize:16,textAlign:'right'},businessSub:{color:'#D9E2DF',textAlign:'right',fontSize:12,marginTop:4},businessArrow:{color:'#fff',fontSize:30},version:{textAlign:'center',color:t.muted,fontSize:11}})
