import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useEffect, useMemo, useState } from 'react';
import { Alert, Linking, ScrollView, StyleSheet, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { api } from '../src/api';
import { audienceLongLabel, effectiveAudience, paletteFor } from '../src/prefs';
import { clearSession, getPrefs, getToken, savePrefs, saveStoredUser } from '../src/session';
import { usePrefs } from '../src/usePrefs';
import { BottomNav, NText, PageTitle, SupportButton } from '../src/ui';

export default function Profile(){const[user,setUser]=useState<any>(null);const[logged,setLogged]=useState(false);const[prefs]=usePrefs();const audience=effectiveAudience(prefs);const t=paletteFor(audience,prefs.appearance);const s=useMemo(()=>styles(t),[audience,prefs.appearance]);const load=async()=>{const tok=await getToken();setLogged(Boolean(tok));if(!tok)return;try{const j=await api('/v1/me');setUser(j.user);await saveStoredUser(j.user);const g=j.user?.profile_gender;if(g==='FEMALE'||g==='MALE'){const stored=(await getPrefs())||prefs;await savePrefs({...stored,profileGender:g,audience:g})}}catch(e:any){if(e.status===401){await clearSession();setLogged(false)}}};useEffect(()=>{load()},[]);
const doLogout=async()=>{try{await api('/v1/auth/logout',{method:'POST'})}catch{}await clearSession();setUser(null);setLogged(false);router.replace('/')};const logout=()=>Alert.alert('خروج از حساب','آیا می‌خواهید از حساب نوبین خارج شوید؟',[{text:'انصراف',style:'cancel'},{text:'خروج',style:'destructive',onPress:doLogout}]);
return <SafeAreaView edges={['top']} style={s.root}><ScrollView contentContainerStyle={s.wrap} showsVerticalScrollIndicator={false}><PageTitle title="حساب" sub="هویت، تنظیمات و مدیریت کسب‌وکار" right={<SupportButton t={t}/>}/>{logged?<><View style={s.user}><View style={s.avatar}><NText weight="bold" style={s.avatarT}>{(user?.name||'ن')[0]}</NText></View><View style={s.userBody}><NText weight="semi" style={s.name}>{user?.name||'کاربر نوبین'}</NText><View style={s.line}><Ionicons name={user?.phone_verified_at?'checkmark-circle-outline':'alert-circle-outline'} size={16} color={user?.phone_verified_at?t.success:t.warning}/><NText style={s.muted}>{user?.phone_verified_at?user.phone:'شماره موبایل تأیید نشده'}</NText></View><View style={s.line}><Ionicons name="chatbubble-ellipses-outline" size={15} color={t.muted}/><NText style={s.muted}>بله: {user?.bale_status==='ACTIVE'?'متصل':'نیاز به اتصال مجدد'}</NText></View></View></View>{!user?.phone_verified_at?<View style={s.warn}><NText weight="medium" style={s.warnT}>برای رزرو نهایی و ثبت کسب‌وکار، شماره موبایل را در بله تأیید کن.</NText><TouchableOpacity style={s.primary} onPress={()=>Linking.openURL('https://ble.ir/nobin_bot?start=phone')}><NText weight="bold" style={s.primaryT}>تأیید شماره در بله</NText></TouchableOpacity><TouchableOpacity onPress={load}><NText weight="medium" style={s.link}>بررسی مجدد وضعیت</NText></TouchableOpacity></View>:null}<View style={s.menu}><Menu icon="options-outline" title="شخصی‌سازی" sub={`${audienceLongLabel(audience)}${prefs.preferredCity?` · ${prefs.preferredCity}`:''}`} onPress={()=>router.push('/preferences')} t={t}/><Menu icon="newspaper-outline" title="بلاگ من" sub="اطلاعیه‌های نوبین و مجموعه‌های دنبال‌شده" onPress={()=>router.push('/blog')} t={t}/><Menu icon="storefront-outline" title="کسب‌وکار من" sub="سالن، پرسنل، خدمات و زمان‌بندی" onPress={()=>router.push('/business-dashboard')} t={t}/><Menu icon="headset-outline" title="ارتباط با پشتیبان" sub="تیکت داخل اپ و پاسخ همزمان از بله" onPress={()=>router.push('/support')} t={t}/></View><TouchableOpacity style={s.logout} onPress={logout}><Ionicons name="log-out-outline" size={17} color={t.danger}/><NText weight="medium" style={s.logoutT}>خروج از حساب</NText></TouchableOpacity></>:<View style={s.empty}><Ionicons name="person-circle-outline" size={42} color={t.muted}/><NText weight="semi" style={s.emptyTitle}>هنوز وارد نشده‌اید</NText><NText style={s.muted}>برای رزرو نهایی و مدیریت نوبت‌ها با بله وارد شوید.</NText><TouchableOpacity style={s.primary} onPress={()=>router.push('/login')}><NText weight="bold" style={s.primaryT}>ورود با بله</NText></TouchableOpacity><TouchableOpacity onPress={()=>router.push('/preferences')}><NText weight="medium" style={s.link}>شخصی‌سازی بدون ورود</NText></TouchableOpacity></View>}<NText style={s.version}>نوبین ۲.۱.۰</NText></ScrollView><BottomNav active="profile" t={t}/></SafeAreaView>}
function Menu({icon,title,sub,onPress,t}:any){return <TouchableOpacity activeOpacity={.72} onPress={onPress} style={{flexDirection:'row-reverse',alignItems:'center',gap:11,paddingVertical:13,paddingHorizontal:13,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:t.line}}><View style={{width:38,height:38,borderRadius:12,backgroundColor:t.accentSoft,alignItems:'center',justifyContent:'center'}}><Ionicons name={icon} size={19} color={t.accent}/></View><View style={{flex:1}}><NText weight="semi" style={{fontSize:13.5,color:t.text,textAlign:'right'}}>{title}</NText><NText style={{fontSize:11.2,lineHeight:18,color:t.muted,textAlign:'right',marginTop:2}}>{sub}</NText></View><Ionicons name="chevron-back" size={17} color={t.muted}/></TouchableOpacity>}
const styles=(t:any)=>StyleSheet.create({root:{flex:1,backgroundColor:t.bg},wrap:{paddingHorizontal:18,paddingTop:10,paddingBottom:24,gap:12},user:{backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:18,padding:14,flexDirection:'row-reverse',gap:11,alignItems:'center'},avatar:{width:50,height:50,borderRadius:16,backgroundColor:t.accentSoft,alignItems:'center',justifyContent:'center'},avatarT:{fontSize:20,color:t.accent},userBody:{flex:1,gap:4},name:{fontSize:15.5,textAlign:'right',color:t.text},line:{flexDirection:'row-reverse',alignItems:'center',gap:5},muted:{fontSize:11.5,lineHeight:19,color:t.muted,textAlign:'right'},warn:{backgroundColor:'#FFF7EC',borderRadius:17,padding:14,gap:9},warnT:{fontSize:12,lineHeight:20,color:'#74501B',textAlign:'right'},primary:{backgroundColor:t.accent,borderRadius:14,paddingVertical:12,paddingHorizontal:15,alignItems:'center'},primaryT:{fontSize:12.5,color:'#fff'},link:{fontSize:11.5,color:t.accent,textAlign:'center'},menu:{backgroundColor:t.card,borderRadius:18,borderWidth:1,borderColor:t.line,overflow:'hidden'},logout:{height:46,borderRadius:15,borderWidth:1,borderColor:t.line,backgroundColor:t.card,flexDirection:'row-reverse',gap:7,alignItems:'center',justifyContent:'center'},logoutT:{fontSize:12.5,color:t.danger},empty:{backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:18,padding:22,alignItems:'center',gap:8},emptyTitle:{fontSize:15,color:t.text},version:{fontSize:10.5,color:t.muted,textAlign:'center',marginTop:4}})
