import { useMemo, useState } from 'react';
import { Alert, StyleSheet, TextInput, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router, useLocalSearchParams } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { api } from '../src/api';
import { effectiveAudience, paletteFor } from '../src/prefs';
import { usePrefs } from '../src/usePrefs';
import { InternalHeader, NText } from '../src/ui';
export default function Review(){const p=useLocalSearchParams<{businessId:string;bookingId:string;businessName?:string}>();const[prefs]=usePrefs();const t=paletteFor(effectiveAudience(prefs),prefs.appearance);const s=useMemo(()=>styles(t),[prefs]);const[rating,setRating]=useState(5);const[comment,setComment]=useState('');const[busy,setBusy]=useState(false);const submit=async()=>{setBusy(true);try{await api('/v1/reviews',{method:'POST',body:JSON.stringify({business_id:Number(p.businessId),booking_id:Number(p.bookingId),rating,comment:comment.trim()})});Alert.alert('ممنون','نظر شما ثبت شد و پس از بررسی نمایش داده می‌شود.',[{text:'باشه',onPress:()=>router.back()}])}catch(e:any){Alert.alert('ثبت نشد',e.message)}finally{setBusy(false)}};return <SafeAreaView edges={['bottom']} style={s.root}><View style={s.wrap}><InternalHeader t={t} title="امتیاز و نظر" sub={p.businessName||'تجربه شما'}/><View style={s.card}><NText weight="bold" style={s.h}>به تجربه‌ات چند ستاره می‌دهی؟</NText><View style={s.stars}>{[1,2,3,4,5].map(n=><TouchableOpacity key={n} onPress={()=>setRating(n)}><Ionicons name={n<=rating?'star':'star-outline'} size={34} color={t.warning}/></TouchableOpacity>)}</View><TextInput multiline value={comment} onChangeText={setComment} placeholder="نظر شما درباره کیفیت خدمت، برخورد، محیط و تجربه رزرو..." placeholderTextColor={t.muted} style={s.area}/><TouchableOpacity disabled={busy} onPress={submit} style={s.btn}><NText weight="bold" style={s.btnT}>{busy?'در حال ثبت...':'ثبت نظر'}</NText></TouchableOpacity></View></View></SafeAreaView>}
const styles=(t:any)=>StyleSheet.create({root:{flex:1,backgroundColor:t.bg},wrap:{padding:16,gap:13},card:{backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:18,padding:15,gap:14},h:{fontSize:15,color:t.text,textAlign:'right'},stars:{flexDirection:'row-reverse',justifyContent:'center',gap:8},area:{minHeight:150,borderWidth:1,borderColor:t.line,borderRadius:13,padding:12,fontFamily:'Vazirmatn_400Regular',color:t.text,textAlign:'right',textAlignVertical:'top'},btn:{height:48,borderRadius:14,backgroundColor:t.accent,alignItems:'center',justifyContent:'center'},btnT:{fontSize:13,color:'#fff'}})
