import { useLocalSearchParams, router } from 'expo-router';
import { ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useEffect, useMemo, useState } from 'react';
import { api } from '../src/api';
import { salonCard } from '../src/live';
import { getPrefs } from '../src/session';
import { audienceLabel, categoriesFor, paletteFor, type Audience } from '../src/prefs';
import type { Salon } from '../src/demo';
export default function Search(){const p=useLocalSearchParams<{q?:string;audience?:string}>();const[q,setQ]=useState(p.q||'');const[audience,setAudience]=useState<Audience>((p.audience as Audience)||'ALL');const[rows,setRows]=useState<Salon[]>([]);const[loading,setLoading]=useState(false);const t=paletteFor(audience);const s=useMemo(()=>styles(t),[audience]);
useEffect(()=>{if(!p.audience)getPrefs().then(v=>v&&setAudience(v.audience))},[p.audience]);
const load=async()=>{setLoading(true);try{const g=audience==='ALL'?'':`&gender=${audience}`;const j=await api(`/v1/businesses?limit=50&q=${encodeURIComponent(q)}${g}`);setRows(Array.isArray(j.items)?j.items.map(salonCard):[])}catch{setRows([])}finally{setLoading(false)}};useEffect(()=>{load()},[audience]);
return <SafeAreaView edges={['bottom']} style={s.root}><ScrollView contentContainerStyle={s.wrap} keyboardShouldPersistTaps="handled"><View style={s.search}><TextInput style={s.input} value={q} onChangeText={setQ} placeholder="خدمت، سالن، شهر یا محله..." onSubmitEditing={load}/><TouchableOpacity style={s.go} onPress={load}><Text style={s.goT}>جستجو</Text></TouchableOpacity></View><View style={s.aud}><Text style={s.muted}>نمایش:</Text>{(['FEMALE','MALE','ALL'] as Audience[]).map(a=><TouchableOpacity key={a} style={[s.chip,audience===a&&s.chipOn]} onPress={()=>setAudience(a)}><Text style={[s.chipT,audience===a&&s.chipTOn]}>{audienceLabel(a)}</Text></TouchableOpacity>)}</View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.quick}>{categoriesFor(audience).slice(0,6).map(x=><TouchableOpacity key={x.t} style={s.quickChip} onPress={()=>{setQ(x.t);setTimeout(load,0)}}><Text>{x.e} {x.t}</Text></TouchableOpacity>)}</ScrollView><View style={s.row}><Text style={s.muted}>{loading?'در حال دریافت...':`${rows.length} نتیجه`}</Text><Text style={s.h}>نتایج</Text></View>{rows.map(x=><TouchableOpacity key={x.id} style={s.card} onPress={()=>router.push(`/business/${x.id}`)}><View style={s.photo}><Text style={s.photoTxt}>{x.name[0]}</Text></View><View style={{flex:1,gap:6}}><Text style={s.name}>{x.name}</Text><Text style={s.muted}>{x.neighborhood?`${x.neighborhood}، `:''}{x.city}</Text><View style={s.badges}>{x.badges.map(b=><Text key={b} style={s.badge}>{b}</Text>)}</View><Text style={s.rating}>★ {x.rating||'—'} · {x.price}</Text><View style={s.slot}><Text style={s.slotT}>{x.next}</Text></View></View></TouchableOpacity>)}{!loading&&!rows.length&&<View style={s.empty}><Text style={s.name}>نتیجه‌ای پیدا نشد</Text><Text style={s.muted}>عبارت یا گروه خدمات دیگری را امتحان کن.</Text></View>}</ScrollView></SafeAreaView>}
const styles=(t:any)=>StyleSheet.create({root:{flex:1,backgroundColor:t.bg},wrap:{padding:18,paddingBottom:35,gap:14},search:{backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:18,padding:6},input:{padding:12,textAlign:'right',fontSize:16,color:t.text},go:{backgroundColor:t.accent,borderRadius:13,padding:11,alignItems:'center'},goT:{color:'#fff',fontWeight:'900'},aud:{flexDirection:'row-reverse',gap:7,flexWrap:'wrap',alignItems:'center'},chip:{borderWidth:1,borderColor:t.line,backgroundColor:t.card,borderRadius:16,paddingHorizontal:10,paddingVertical:8},chipOn:{backgroundColor:t.accent,borderColor:t.accent},chipT:{color:t.ink,fontWeight:'700',fontSize:12},chipTOn:{color:'#fff'},quick:{gap:8},quickChip:{borderWidth:1,borderColor:t.line,backgroundColor:t.card,borderRadius:15,paddingHorizontal:12,paddingVertical:9},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},h:{fontSize:19,fontWeight:'900',color:t.text},muted:{color:t.muted,textAlign:'right',lineHeight:22},card:{flexDirection:'row-reverse',gap:12,backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:22,padding:12},photo:{width:92,height:112,borderRadius:18,backgroundColor:t.accentSoft,alignItems:'center',justifyContent:'center'},photoTxt:{fontSize:34,fontWeight:'900',color:t.accent},name:{fontSize:17,fontWeight:'900',textAlign:'right',color:t.text},badges:{flexDirection:'row-reverse',gap:5,flexWrap:'wrap'},badge:{fontSize:11,backgroundColor:t.accentSoft,paddingHorizontal:8,paddingVertical:4,borderRadius:10,color:t.muted},rating:{textAlign:'right',color:t.warning,fontWeight:'700'},slot:{alignSelf:'flex-end',backgroundColor:'#EAF7F0',borderRadius:10,paddingHorizontal:8,paddingVertical:5},slotT:{fontSize:11,color:t.success,fontWeight:'800'},empty:{backgroundColor:t.card,padding:24,borderRadius:20,alignItems:'center',gap:6}})
