import { Ionicons } from '@expo/vector-icons';
import { useLocalSearchParams, router } from 'expo-router';
import { Image, ScrollView, StyleSheet, TextInput, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useEffect, useMemo, useState } from 'react';
import { api } from '../src/api';
import { salonCard } from '../src/live';
import { audienceLongLabel, categoriesFor, effectiveAudience, paletteFor } from '../src/prefs';
import { usePrefs } from '../src/usePrefs';
import { BottomNav, NText, PageTitle, Pill } from '../src/ui';
import type { Salon } from '../src/demo';

export default function Search(){
  const p=useLocalSearchParams<{q?:string}>();const[q,setQ]=useState(p.q||'');const[prefs]=usePrefs();const[rows,setRows]=useState<Salon[]>([]);const[loading,setLoading]=useState(false);const audience=effectiveAudience(prefs);const t=paletteFor(audience,prefs.appearance);const s=useMemo(()=>styles(t),[audience,prefs.appearance]);
  const load=async(nextQ=q)=>{setLoading(true);try{const g=audience==='ALL'?'':`&gender=${audience}`;const location=prefs.preferredCity||prefs.preferredProvince||'';const query=[nextQ,location].filter(Boolean).join(' ');const j=await api(`/v1/businesses?limit=50&q=${encodeURIComponent(query)}${g}`);setRows(Array.isArray(j.items)?j.items.map(salonCard):[])}catch{setRows([])}finally{setLoading(false)}};
  useEffect(()=>{load(p.q||'')},[audience,prefs.preferredProvince,prefs.preferredCity]);
  return <SafeAreaView edges={['top']} style={s.root}><ScrollView contentContainerStyle={s.wrap} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}>
    <PageTitle title="جستجو" sub={`فقط ${audienceLongLabel(audience)} نمایش داده می‌شود`}/>
    <View style={s.filterLine}><Pill t={t} icon="person-outline">{audienceLongLabel(audience)}</Pill><Pill t={t} icon="location-outline" onPress={()=>router.push('/location-filter')}>{prefs.preferredCity||prefs.preferredProvince||'سراسر ایران'}</Pill></View>
    <View style={s.search}><TouchableOpacity activeOpacity={.75} onPress={()=>load()} style={s.searchBtn}><Ionicons name="search" size={19} color="#fff"/></TouchableOpacity><TextInput returnKeyType="search" onSubmitEditing={()=>load()} style={s.input} value={q} onChangeText={setQ} placeholder="خدمت، سالن یا محله..." placeholderTextColor={t.muted}/><Ionicons name="search-outline" size={19} color={t.muted}/></View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.quick}>{categoriesFor(audience).slice(0,7).map(x=><TouchableOpacity activeOpacity={.72} key={x.t} style={s.quickChip} onPress={()=>{setQ(x.t);load(x.t)}}><Ionicons name={x.icon as any} size={16} color={t.accent}/><NText weight="medium" style={s.quickT}>{x.t}</NText></TouchableOpacity>)}</ScrollView>
    <View style={s.resultHead}><NText style={s.count}>{loading?'در حال دریافت...':`${rows.length} نتیجه`}</NText><NText weight="bold" style={s.h}>نتایج</NText></View>
    {rows.map(x=><TouchableOpacity activeOpacity={.76} key={x.id} style={s.card} onPress={()=>router.push(`/business/${x.id}`)}>{x.coverUrl?<Image source={{uri:x.coverUrl}} style={s.photo}/>:<View style={[s.photo,s.photoFallback]}><NText weight="extra" style={s.photoTxt}>{x.name[0]}</NText></View>}<View style={s.body}><NText weight="semi" numberOfLines={1} style={s.name}>{x.name}</NText><NText numberOfLines={1} style={s.muted}>{x.neighborhood?`${x.neighborhood}، `:''}{x.city}</NText><View style={s.meta}><View style={s.rating}><Ionicons name="star" size={13} color={t.warning}/><NText weight="medium" style={{fontSize:10.5,color:t.warning}}>{x.rating||'—'}</NText></View>{x.badges[0]?<NText weight="medium" style={s.badge}>{x.badges[0]}</NText>:null}</View></View><Ionicons name="chevron-back" size={18} color={t.muted}/></TouchableOpacity>)}
    {!loading&&!rows.length?<View style={s.empty}><Ionicons name="search-outline" size={28} color={t.muted}/><NText weight="semi" style={s.emptyTitle}>نتیجه‌ای پیدا نشد</NText><NText style={s.muted}>عبارت کوتاه‌تر، شهر دیگر یا گروه خدمات دیگری را امتحان کن.</NText></View>:null}
  </ScrollView><BottomNav active="search" t={t}/></SafeAreaView>
}
const styles=(t:any)=>StyleSheet.create({root:{flex:1,backgroundColor:t.bg},wrap:{paddingHorizontal:18,paddingTop:10,paddingBottom:24,gap:13},filterLine:{flexDirection:'row-reverse',gap:7,flexWrap:'wrap'},search:{height:52,backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:17,paddingHorizontal:8,flexDirection:'row',alignItems:'center',gap:8},searchBtn:{width:38,height:38,borderRadius:13,backgroundColor:t.accent,alignItems:'center',justifyContent:'center'},input:{flex:1,textAlign:'right',fontFamily:'Vazirmatn_400Regular',fontSize:13.5,color:t.text},quick:{gap:7},quickChip:{height:36,flexDirection:'row-reverse',alignItems:'center',gap:5,borderWidth:1,borderColor:t.line,backgroundColor:t.card,borderRadius:14,paddingHorizontal:10},quickT:{fontSize:11.5,color:t.text},resultHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:3},count:{fontSize:11.5,color:t.muted},h:{fontSize:17.5,color:t.text},card:{minHeight:86,flexDirection:'row-reverse',alignItems:'center',gap:10,backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:18,padding:10},photo:{width:62,height:62,borderRadius:15},photoFallback:{backgroundColor:t.accentSoft,alignItems:'center',justifyContent:'center'},photoTxt:{fontSize:24,color:t.accent},body:{flex:1,gap:3},name:{fontSize:14.5,color:t.text,textAlign:'right'},muted:{fontSize:11.5,lineHeight:18,color:t.muted,textAlign:'right'},meta:{flexDirection:'row-reverse',gap:8,alignItems:'center'},rating:{flexDirection:'row-reverse',gap:3,alignItems:'center'},badge:{fontSize:9.5,color:t.accent,backgroundColor:t.accentSoft,paddingHorizontal:7,paddingVertical:3,borderRadius:9},empty:{backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:18,padding:22,alignItems:'center',gap:6},emptyTitle:{fontSize:15,color:t.text}})
