import { useEffect, useMemo, useState } from 'react';
import { Alert, ScrollView, StyleSheet, TextInput, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { api } from '../src/api';
import { effectiveAudience, paletteFor } from '../src/prefs';
import { usePrefs } from '../src/usePrefs';
import { InternalHeader, NText } from '../src/ui';

export default function Support(){
  const[prefs]=usePrefs(); const t=paletteFor(effectiveAudience(prefs),prefs.appearance); const s=useMemo(()=>styles(t),[prefs]);
  const[items,setItems]=useState<any[]>([]); const[selected,setSelected]=useState<any>(null); const[subject,setSubject]=useState(''); const[body,setBody]=useState(''); const[busy,setBusy]=useState(false);
  const load=async()=>{try{const j=await api('/v1/support/tickets');setItems(j.items||[])}catch(e:any){Alert.alert('خطا',e.message)}};
  useEffect(()=>{load()},[]);
  const open=async(id:number)=>{try{const j=await api('/v1/support/tickets/'+id);setSelected(j.ticket)}catch(e:any){Alert.alert('خطا',e.message)}};
  const sendNew=async()=>{if(!body.trim())return;setBusy(true);try{const j=await api('/v1/support/tickets',{method:'POST',body:JSON.stringify({subject:subject.trim()||'پشتیبانی نوبین',body:body.trim()})});setSubject('');setBody('');await load();await open(j.ticket_id)}catch(e:any){Alert.alert('ارسال نشد',e.message)}finally{setBusy(false)}};
  const reply=async()=>{if(!selected||!body.trim())return;setBusy(true);try{await api('/v1/support/tickets/'+selected.id+'/messages',{method:'POST',body:JSON.stringify({body:body.trim()})});setBody('');await open(selected.id);await load()}catch(e:any){Alert.alert('ارسال نشد',e.message)}finally{setBusy(false)}};
  return <SafeAreaView edges={['bottom']} style={s.root}><ScrollView contentContainerStyle={s.wrap}><InternalHeader t={t} title="پشتیبانی" sub="تیکت داخل اپ و پاسخ همزمان از ربات بله"/>
    {selected?<><TouchableOpacity onPress={()=>setSelected(null)}><NText weight="semi" style={s.link}>بازگشت به تیکت‌ها</NText></TouchableOpacity><View style={s.card}><NText weight="bold" style={s.title}>{selected.subject}</NText><NText style={s.muted}>#{selected.id} · {selected.status}</NText></View>{(selected.messages||[]).map((m:any)=><View key={m.id} style={[s.msg,m.sender_role==='ADMIN'&&s.admin]}><NText style={s.msgRole}>{m.sender_role==='ADMIN'?'پشتیبان نوبین':'شما'}</NText><NText style={s.msgBody}>{m.body}</NText></View>)}<TextInput multiline value={body} onChangeText={setBody} placeholder="پاسخ خود را بنویس..." placeholderTextColor={t.muted} style={s.area}/><TouchableOpacity disabled={busy} onPress={reply} style={s.btn}><NText weight="bold" style={s.btnT}>{busy?'در حال ارسال...':'ارسال پاسخ'}</NText></TouchableOpacity></>:<><View style={s.card}><NText weight="bold" style={s.title}>تیکت جدید</NText><TextInput value={subject} onChangeText={setSubject} placeholder="موضوع" placeholderTextColor={t.muted} style={s.input}/><TextInput multiline value={body} onChangeText={setBody} placeholder="پیام شما..." placeholderTextColor={t.muted} style={s.area}/><TouchableOpacity disabled={busy} onPress={sendNew} style={s.btn}><NText weight="bold" style={s.btnT}>ارسال به پشتیبانی</NText></TouchableOpacity></View><NText weight="bold" style={s.heading}>تیکت‌های قبلی</NText>{items.map(x=><TouchableOpacity key={x.id} onPress={()=>open(Number(x.id))} style={s.ticket}><View style={{flex:1}}><NText weight="semi" style={s.title}>{x.subject}</NText><NText numberOfLines={1} style={s.muted}>{x.last_message||''}</NText></View><NText style={s.status}>{x.status}</NText></TouchableOpacity>)}</>}
  </ScrollView></SafeAreaView>
}
const styles=(t:any)=>StyleSheet.create({root:{flex:1,backgroundColor:t.bg},wrap:{padding:16,gap:10},card:{backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:17,padding:13,gap:8},title:{fontSize:14,color:t.text,textAlign:'right'},muted:{fontSize:10.8,lineHeight:18,color:t.muted,textAlign:'right'},heading:{fontSize:16,color:t.text,textAlign:'right',marginTop:4},ticket:{backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:15,padding:12,flexDirection:'row-reverse',alignItems:'center',gap:8},status:{fontSize:9.5,color:t.accent,backgroundColor:t.accentSoft,paddingHorizontal:8,paddingVertical:5,borderRadius:9},input:{height:46,borderWidth:1,borderColor:t.line,borderRadius:12,paddingHorizontal:11,fontFamily:'Vazirmatn_400Regular',color:t.text,textAlign:'right'},area:{minHeight:110,borderWidth:1,borderColor:t.line,borderRadius:12,padding:11,fontFamily:'Vazirmatn_400Regular',color:t.text,textAlign:'right',textAlignVertical:'top'},btn:{height:46,borderRadius:13,backgroundColor:t.accent,alignItems:'center',justifyContent:'center'},btnT:{fontSize:12.5,color:'#fff'},msg:{alignSelf:'flex-start',maxWidth:'88%',backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:15,padding:11,gap:3},admin:{alignSelf:'flex-end',backgroundColor:t.accentSoft,borderColor:t.accentSoft},msgRole:{fontSize:9.5,color:t.accent,textAlign:'right'},msgBody:{fontSize:12,lineHeight:21,color:t.text,textAlign:'right'},link:{fontSize:11.5,color:t.accent,textAlign:'right'}})
