import { useLocalSearchParams, router } from 'expo-router';
import { useEffect, useMemo, useState } from 'react';
import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { api } from '../../src/api';
import { getPrefs } from '../../src/session';
import { paletteFor, type Audience } from '../../src/prefs';
const fa=new Intl.NumberFormat('fa-IR');const money=(n:any)=>`${fa.format(Number(n||0))} تومان`;
export default function Business(){const{id}=useLocalSearchParams<{id:string}>();const[b,setB]=useState<any>(null);const[audience,setAudience]=useState<Audience>('ALL');const t=paletteFor(audience);const s=useMemo(()=>styles(t),[audience]);useEffect(()=>{getPrefs().then(p=>p&&setAudience(p.audience));api(`/v1/businesses/${id}`).then(j=>setB(j.business)).catch(()=>{})},[id]);if(!b)return <SafeAreaView edges={['bottom']} style={s.root}><Text style={s.loading}>در حال دریافت اطلاعات...</Text></SafeAreaView>;const services=(b.services||[]).filter((x:any)=>audience==='ALL'||x.gender==='ALL'||x.gender===audience);return <SafeAreaView edges={['bottom']} style={s.root}><ScrollView contentContainerStyle={s.wrap}><View style={s.cover}><Text style={s.coverT}>{b.name?.[0]||'ن'}</Text></View><View style={s.head}><Text style={s.name}>{b.name}</Text><Text style={s.rating}>★ {b.average_rating||'—'} · {fa.format(Number(b.rating_count||0))} نظر</Text><Text style={s.muted}>{[b.address,b.city].filter(Boolean).join('، ')} · {b.gender==='MALE'?'آقایان':b.gender==='FEMALE'?'بانوان':'همه'}</Text>{b.verified? <Text style={s.badge}>تأییدشده</Text>:null}</View><Text style={s.h}>خدمات قابل نمایش برای شما</Text>{services.map((sv:any)=><TouchableOpacity key={sv.id} style={s.service} onPress={()=>router.push({pathname:'/booking',params:{businessId:String(b.id),serviceId:String(sv.id)}})}><View><Text style={s.price}>{money(sv.price)}</Text><Text style={s.time}>{fa.format(Number(sv.duration_minutes||0))} دقیقه</Text></View><View style={{flex:1}}><Text style={s.serviceName}>{sv.title}</Text><Text style={s.muted}>{Number(sv.deposit_amount)>0?`بیعانه ${money(sv.deposit_amount)}`:'بدون بیعانه'}</Text></View></TouchableOpacity>)}{!services.length&&<View style={s.info}><Text style={s.muted}>خدمتی متناسب با پروفایل انتخابی شما ثبت نشده است. از حساب، «همه خدمات» را انتخاب کنید.</Text></View>}<View style={s.info}><Text style={s.h}>رزرو چگونه انجام می‌شود؟</Text><Text style={s.muted}>خدمت را انتخاب کن، متخصص یا «اولین متخصص آزاد» را تعیین کن، روز و زمان آزاد واقعی را ببین و بعد از تأیید شماره موبایل رزرو را ثبت کن.</Text></View></ScrollView></SafeAreaView>}
const styles=(t:any)=>StyleSheet.create({root:{flex:1,backgroundColor:t.bg},wrap:{padding:18,paddingBottom:40,gap:14},loading:{padding:22,textAlign:'center',color:t.muted},cover:{height:180,borderRadius:28,backgroundColor:t.accentSoft,alignItems:'center',justifyContent:'center'},coverT:{fontSize:64,fontWeight:'900',color:t.accent},head:{backgroundColor:t.card,borderRadius:22,borderWidth:1,borderColor:t.line,padding:16,gap:7},name:{fontSize:23,fontWeight:'900',textAlign:'right',color:t.text},rating:{color:t.warning,fontWeight:'800',textAlign:'right'},muted:{color:t.muted,textAlign:'right',lineHeight:22},badge:{alignSelf:'flex-end',backgroundColor:t.accentSoft,color:t.accent,borderRadius:10,paddingHorizontal:9,paddingVertical:5,fontSize:11,fontWeight:'800'},h:{fontSize:19,fontWeight:'900',textAlign:'right',color:t.text},service:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:12,backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:20,padding:15},serviceName:{fontSize:16,fontWeight:'900',textAlign:'right',color:t.text},price:{color:t.accent,fontWeight:'900'},time:{fontSize:11,color:t.muted,marginTop:5},info:{backgroundColor:t.card,borderRadius:20,padding:16,gap:8,borderWidth:1,borderColor:t.line}})
